DESERT: UWIPModule Class Reference
UWIPModule Class Reference
#include <uwip-module.h>
Public Member Functions
UWIPModule ()
virtual ~UWIPModule ()=default
virtual void recv (Packet *p)
virtual int command (int argc, const char *const *argv)
virtual int recvSyncClMsg (ClMessage *m)
void printIdsPkts () const
Static Public Member Functions
static const string printIP (const nsaddr_t &)
static const string printIP (const uint8_t &)
Static Protected Member Functions
static int getIpHeaderSize ()
Protected Attributes
uint8_t ipAddr_
int debug_
bool addr_type_inet
Static Protected Attributes
static uint8_t lastIP = 0
Detailed Description
UWIPModule class is used to define the Internet Protocol (IP) layer of a node.
Constructor & Destructor Documentation
UWIPModule()
UWIPModule::UWIPModule ()
Constructor of UWIPModule class.
References debug_, ipAddr_, and lastIP.
~UWIPModule()
virtual UWIPModule::~UWIPModule () virtual default
Destructor of UWIPModule class.
Member Function Documentation
command()
int UWIPModule::command (int argc, const char *const * argv) virtual
TCL command interpreter. It implements the following OTcl methods:
Parameters
argc Number of arguments in argv.
argv Array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not.
Reimplemented in UwStaticRoutingModule.
References addr_type_inet, getIpHeaderSize(), ipAddr_, printIdsPkts(), and printIP().
getIpHeaderSize()
static int UWIPModule::getIpHeaderSize () inline static protected
Returns the size in byte of a hdr_sun_data packet header.
Returns
The size of a hdr_sun_data packet header.
Referenced by command().
printIdsPkts()
void UWIPModule::printIdsPkts () const inline
Prints the IDs of the packet's headers defined by UWIP.
References PT_UWIP.
Referenced by command().
printIP() [1/2]
const string UWIPModule::printIP (const nsaddr_t & ip_) static
Returns a string with an IP in the classic form "x.x.x.x" converting an ns2 nsaddr_t address.
Parameters
nsaddr_t& ns2 address
Returns
String that contains a printable IP in the classic form "x.x.x.x"
Referenced by command().
printIP() [2/2]
const string UWIPModule::printIP (const uint8_t & ip_) static
Returns a string with an IP in the classic form "x.x.x.x" converting an uint8_t address.
Parameters
uint8_t& address
Returns
String that contains a printable IP in the classic form "x.x.x.x"
recv()
void UWIPModule::recv (Packet * p) virtual
Performs the reception of packets from upper and lower layers.
Parameters
Packet* Pointer to the packet received.
Reimplemented in UwStaticRoutingModule.
References addr_type_inet, hdr_uwip::daddr(), ipAddr_, and hdr_uwip::saddr().
recvSyncClMsg()
int UWIPModule::recvSyncClMsg (ClMessage * m) virtual
Cross-Layer messages synchronous interpreter.
Parameters
ClMessage* an instance of ClMessage that represent the message received
Returns
0 if successful.
References ipAddr_, UWIPClMsgSendAddr::setAddr(), and UWIP_CLMSG_SEND_ADDR.
Member Data Documentation
addr_type_inet
bool UWIPModule::addr_type_inet protected
true if the addressing type is INET, false if it is ILINK.
Referenced by command(), and recv().
debug_
int UWIPModule::debug_ protected
Flag to enable or disable dirrefent levels of debug.
Referenced by UWIPModule().
ipAddr_
uint8_t UWIPModule::ipAddr_ protected
IP address of the node.
Referenced by command(), recv(), recvSyncClMsg(), and UWIPModule().
lastIP
uint8_t UWIPModule::lastIP = 0 static protected
Used to set a default IP address.
Referenced by UWIPModule().
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/network/uwip/uwip-module.h
DESERT_Framework/DESERT/network/uwip/uwip-module.cpp