DESERT: packerUWUDP Class Reference
packerUWUDP Class Reference
#include <packer-uwudp.h>
Public Member Functions
packerUWUDP ()
~packerUWUDP ()
Public Member Functions inherited from packer
packer (bool)
~packer ()
int command (int, const char *const *)
size_t getPayloadBytesLength ()
size_t getHdrBytesLength ()
size_t getPayloadBinLength ()
size_t getHdrBinLength ()
std::string packPayload (Packet *)
std::string packHdr (Packet *)
Packet * unpackPayload (Packet *)
Packet * unpackHdr (Packet *)
void printMap ()
Private Member Functions
void init ()
size_t packMyHdr (Packet *, unsigned char *, size_t)
size_t unpackMyHdr (unsigned char *, size_t, Packet *)
void printMyHdrMap ()
void printMyHdrFields (Packet *)
Private Attributes
size_t SPort_Bits
size_t DPort_Bits
Additional Inherited Members
Static Public Member Functions inherited from packer
template<typename T >
static T restoreSignedValue (T _header_field, const uint32_t &_num_compressed_bits)
static std::string hexdump_nice (std::string)
static std::string hexdump_nice (const char *, size_t)
static std::string hexdump (std::string)
static std::string hex_bytes (float)
static std::string hex_bytes (double)
static std::string hex_bytes (const char &, const uint32_t &)
static std::string hex_bytes (const int8_t &, const uint32_t &)
static std::string hex_bytes (const int16_t &, const uint32_t &)
static std::string hex_bytes (const int32_t &, const uint32_t &)
static std::string hex_bytes (const int64_t &, const uint32_t &)
static std::string hex_bytes (const uint8_t &, const uint32_t &)
static std::string hex_bytes (const uint16_t &, const uint32_t &)
static std::string hex_bytes (const uint32_t &, const uint32_t &)
static std::string hex_bytes (const uint64_t &, const uint32_t &)
static std::string hexdump (const char *, size_t)
static std::string bindump (std::string)
static std::string bindump (const char *, size_t)
Protected Member Functions inherited from packer
virtual void printMyHdrField (Packet *, int)
size_t getMyHdrBinLength ()
size_t get (unsigned char *buffer, size_t offset, void *val, size_t h)
size_t put (unsigned char *buffer, size_t offset, void *val, size_t h)
Protected Attributes inherited from packer
std::vector< size_t > n_bits
int debug_
Detailed Description
Class exploited by the Uwal module to map an NS-Miracle packet into a bit stream, and vice-versa.
Constructor & Destructor Documentation
packerUWUDP()
packerUWUDP::packerUWUDP ()
Class constructor.
References packer::debug_, DPort_Bits, packer::n_bits, and SPort_Bits.
~packerUWUDP()
packerUWUDP::~packerUWUDP ()
Class destructor.
Member Function Documentation
init()
void packerUWUDP::init () private virtual
Init the Packer
Reimplemented from packer.
References packer::debug_, DPort_Bits, packer::n_bits, and SPort_Bits.
packMyHdr()
size_t packerUWUDP::packMyHdr (Packet * p, unsigned char * buf, size_t offset) private virtual
Method to transform the headers of Uwpolling into a stream of bits
Parameters
Pointer to the packet to serialize
Pointer to the buffer
Offset from the begin of the buffer
Returns
New offset after packing the headers of the packets
Reimplemented from packer.
References packer::debug_, hdr_uwudp::dport_, packer::n_bits, printMyHdrFields(), packer::put(), and hdr_uwudp::sport_.
printMyHdrFields()
void packerUWUDP::printMyHdrFields (Packet * p) private virtual
Method used for debug purposes. It prints the value of the headers of a packet
Parameters
Pointer of the packet
Reimplemented from packer.
References hdr_uwudp::dport(), packer::hex_bytes(), packer::n_bits, and hdr_uwudp::sport().
Referenced by packMyHdr(), and unpackMyHdr().
printMyHdrMap()
void packerUWUDP::printMyHdrMap () private virtual
Method used for debug purposes. It prints the number of bits for each header serialized
Reimplemented from packer.
References DPort_Bits, and SPort_Bits.
unpackMyHdr()
size_t packerUWUDP::unpackMyHdr (unsigned char * buf, size_t offset, Packet * p) private virtual
Method responsible to take the informations from the received buffer and store it into the headers of the packet
Parameters
Pointer to the buffer received
Offset from the begin of the buffer
Pointer to the new packet
Returns
New offset after unpacking the headers
Reimplemented from packer.
References packer::debug_, hdr_uwudp::dport(), hdr_uwudp::dport_, packer::get(), packer::n_bits, printMyHdrFields(), hdr_uwudp::sport(), and hdr_uwudp::sport_.
Member Data Documentation
DPort_Bits
size_t packerUWUDP::DPort_Bits private
Bit length of the sport_ field to be put in the header stream of bits.
Referenced by init(), packerUWUDP(), and printMyHdrMap().
SPort_Bits
size_t packerUWUDP::SPort_Bits private
Referenced by init(), packerUWUDP(), and printMyHdrMap().
The documentation for this class was generated from the following files:
DESERT_Addons/packer_uwudp/packer-uwudp.h
DESERT_Addons/packer_uwudp/packer-uwudp.cpp