DESERT: UwSCROVCtrModule Class Reference
UwSCROVCtrModule Class Reference
#include <uwsc-rovctr-module.h>
Public Member Functions
UwSCROVCtrModule ()
virtual ~UwSCROVCtrModule ()=default
virtual int command (int argc, const char *const *argv) override
virtual void recv (Packet *) override
virtual int recvSyncClMsg (ClMessage *m) override
Public Member Functions inherited from UwROVCtrModule
UwROVCtrModule ()
virtual ~UwROVCtrModule ()=default
virtual void initPkt (Packet *p) override
void reset_retx ()
virtual void recv (Packet *p, Handler *h) override
virtual void transmit () override
virtual void start () override
Public Member Functions inherited from UwCbrModule
UwCbrModule ()
virtual ~UwCbrModule ()=default
virtual double GetRTT () const
virtual double GetFTT () const
virtual double GetTxTime () const
virtual double GetPER () const
virtual double GetTHR () const
virtual double GetRTTstd () const
virtual double GetFTTstd () const
virtual void resetStats ()
void printIdsPkts () const
Protected Attributes
int leader_id
bool rov_status
Protected Attributes inherited from UwROVCtrModule
int sn
int adaptiveRTO
double adaptiveRTO_parameter
float x_rov
float y_rov
float z_rov
float newX
float newY
float newZ
float speed
Position * posit
Packet * pkt
Protected Attributes inherited from UwCbrModule
uint16_t dstPort_
std::string log_suffix
nsaddr_t dstAddr_
char priority_
std::ofstream tracefile
std::string tracefilename
bool * sn_check
int PoissonTraffic_
int debug_
int drop_out_of_order_
uint traffic_type_
UwSendTimer sendTmr_
int txsn
int hrsn
int pkts_recv
int pkts_ooseq
int pkts_lost
int pkts_invalid
int pkts_last_reset
int cnt
double rftt
double srtt
double sftt
double lrtime
double sthr
double period_
int pktSize_
double sumrtt
double sumrtt2
int rttsamples
double sumftt
double sumftt2
int fttsamples
double sumtxtimes = 0
double sumbytes
double sumdt
uint32_t esn
int tracefile_enabler_
Additional Inherited Members
Static Public Member Functions inherited from UwROVCtrModule
static int getROVMonHeaderSize ()
static int getROVCTRHeaderSize ()
Protected Member Functions inherited from UwCbrModule
virtual void sendPkt ()
virtual void sendPktLowPriority ()
virtual void sendPktHighPriority ()
virtual void stop ()
virtual void updateRTT (const double &)
virtual void updateFTT (const double &)
virtual void updateThroughput (const int &, const double &)
virtual void incrPktLost (const int &)
virtual void incrPktRecv ()
virtual void incrPktOoseq ()
virtual void incrPktInvalid ()
virtual double getTimeBeforeNextPkt ()
virtual void printReceivedPacket (Packet *p)
Static Protected Member Functions inherited from UwCbrModule
static int getCbrHeaderSize ()
Static Protected Attributes inherited from UwCbrModule
static int uidcnt_ = 0
Detailed Description
UwSCROVCtrModule class adds to the UwROVCtrModule class the possibility to receive and send cross layer messages.
Constructor & Destructor Documentation
UwSCROVCtrModule()
UwSCROVCtrModule::UwSCROVCtrModule ()
Constructor of UwSCROVCtrModule class.
~UwSCROVCtrModule()
virtual UwSCROVCtrModule::~UwSCROVCtrModule () virtual default
Destructor of UwSCROVCtrModule class.
Member Function Documentation
command()
int UwSCROVCtrModule::command (int argc, const char *const * argv) override virtual
TCL command interpreter. It implements the following OTcl methods:
Parameters
argc Number of arguments in argv.
argv Array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not.
Reimplemented from UwROVCtrModule.
References UwROVCtrModule::command(), leader_id, UwROVCtrModule::newX, UwROVCtrModule::newY, UwROVCtrModule::newZ, UwROVCtrModule::reset_retx(), rov_status, UwROVCtrModule::speed, and UwROVCtrModule::transmit().
recv()
void UwSCROVCtrModule::recv (Packet * p) override virtual
Performs the reception of packets from upper and lower layers.
Parameters
Packet* Pointer to the packet will be received.
Reimplemented from UwROVCtrModule.
References UwCbrModule::debug_, leader_id, UwROVCtrModule::recv(), ClMsgCtr2McPosition::setRovPosition(), hdr_uwROV_monitoring::x(), hdr_uwROV_monitoring::y(), and hdr_uwROV_monitoring::z().
recvSyncClMsg()
int UwSCROVCtrModule::recvSyncClMsg (ClMessage * m) override virtual
Recv syncronous cross layer messages to require an operation from another module.
Parameters
m Pointer cross layer message
Returns
int Zero if successful
References CLMSG_MC2CTR_SETPOS, CLMSG_MC2CTR_SETSTATUS, UwCbrModule::debug_, UwROVCtrModule::newX, UwROVCtrModule::newY, UwROVCtrModule::newZ, UwROVCtrModule::reset_retx(), rov_status, UwROVCtrModule::transmit(), UwROVCtrModule::x_rov, UwROVCtrModule::y_rov, and UwROVCtrModule::z_rov.
Member Data Documentation
leader_id
int UwSCROVCtrModule::leader_id protected
Id of the Mission Coordinator module.
Referenced by command(), and recv().
rov_status
bool UwSCROVCtrModule::rov_status protected
Status of the ROV follower, true if detected a mine
Referenced by command(), and recvSyncClMsg().
The documentation for this class was generated from the following files:
DESERT_Addons/uwswarm_control/uwsc-rovctr-module.h
DESERT_Addons/uwswarm_control/uwsc-rovctr-module.cc