DESERT: CheckTimer Class Reference
CheckTimer Class Reference
#include <uwmodem.h>
Public Member Functions
CheckTimer (UwModem *pmModem_)
CheckTimer (UWMPhy_modem *pmModem_)
CheckTimer (UWMPhy_modem *pmModem_)
Protected Member Functions
virtual void expire (Event *e)
virtual void expire (Event *e)
virtual void expire (Event *e)
Protected Attributes
UwModem * pmModem
UWMPhy_modem * pmModem
Detailed Description
The class used by UwModem to handle simulator's event expirations; it is exploited to schedule the reading process from the modem; see the ns2 manual for more details about TimerHandler.
The class used by UWMPhy_modem to handle simulator's event expirations; it is exploited to schedule the reading process from the modem; see the ns2 manual for more details about TimerHandler.
Constructor & Destructor Documentation
CheckTimer() [1/3]
CheckTimer::CheckTimer (UwModem * pmModem_) inline
Class constructor.
Parameters
pmModem_ pointer to the UwModem object to link with this CheckTimer object.
References UwModem::getDebug(), and pmModem.
CheckTimer() [2/3]
CheckTimer::CheckTimer (UWMPhy_modem * pmModem_) inline
Class constructor.
Parameters
pmModem_ pointer to the UWMPhy_modem object to link with this CheckTimer object.
References UwModem::getDebug(), and pmModem.
CheckTimer() [3/3]
CheckTimer::CheckTimer (UWMPhy_modem * pmModem_) inline
Class constructor.
Parameters
pmModem_ pointer to the UWMPhy_modem object to link with this CheckTimer object.
References UwModem::getDebug(), and pmModem.
Member Function Documentation
expire() [1/3]
virtual void CheckTimer::expire (Event * e) protected virtual
Method to handle the expiration of a given event.
Parameters
e event to be handled.
expire() [2/3]
void CheckTimer::expire (Event * e) protected virtual
Method to handle the expiration of a given event.
Parameters
e event to be handled.
References UwModem::checkEvent(), and pmModem.
expire() [3/3]
virtual void CheckTimer::expire (Event * e) protected virtual
Method to handle the expiration of a given event.
Parameters
e event to be handled.
Member Data Documentation
pmModem [1/2]
UWMPhy_modem * CheckTimer::pmModem protected
Pointer to an UwModem object. It is used to call UwModem::checkEvent() when the countdown expires.
Pointer to an UWMPhy_modem object. It is used to call UWMPhy_modem::check_modem() when the countdown expires.
Referenced by CheckTimer(), CheckTimer(), and expire().
pmModem [2/2]
UWMPhy_modem* CheckTimer::pmModem protected
Pointer to an UWMPhy_modem object. It is used to call UWMPhy_modem::check_modem() when the countdown expires.
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/physical/uwmodem/uwmodem.h
DESERT_Framework/DESERT/physical/uwmphy_modem/uwmphy_modem.h
DESERT_Addons/uwmphy_modem/uwmphy_modem.h
DESERT_Framework/DESERT/physical/uwmodem/uwmodem.cpp
DESERT_Framework/DESERT/physical/uwmphy_modem/uwmphy_modem.cpp
DESERT_Addons/uwmphy_modem/uwmphy_modem.cpp