DESERT: UwElectroMagneticMPropagation Class Reference
UwElectroMagneticMPropagation Class Reference
#include <uwem-mpropagation.h>
Public Member Functions
UwElectroMagneticMPropagation ()
virtual ~UwElectroMagneticMPropagation ()
virtual int command (int, const char *const *)
virtual double getGain (Packet *p)
Public Attributes
int debug_
Protected Member Functions
void getRelativePermittivity (double f_, double *rel_e)
double getSigmaSW ()
double getAlpha (double *rel_e, double w, double sigma)
double getBeta (double *rel_e, double w, double sigma)
void getEtaW (double *etaW, double *rel_e, double w, double sigma)
double getModTauSquared (double *etaW)
Protected Attributes
double T_
double S_
Detailed Description
Class used to represents the UWOPTICAL_MPROPAGATION.
Constructor & Destructor Documentation
UwElectroMagneticMPropagation()
UwElectroMagneticMPropagation::UwElectroMagneticMPropagation ()
Constructor of the UwElectroMagneticMPropagation class
References debug_, S_, and T_.
~UwElectroMagneticMPropagation()
virtual UwElectroMagneticMPropagation::~UwElectroMagneticMPropagation () inline virtual
Destructor of the UwElectroMagneticMPropagation class
Member Function Documentation
command()
int UwElectroMagneticMPropagation::command (int argc, const char *const * argv) virtual
TCL command interpreter. It implements the following OTcl methods:
Parameters
argc Number of arguments in argv.
argv Array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not.
References S_, and T_.
getAlpha()
double UwElectroMagneticMPropagation::getAlpha (double * rel_e, double w, double sigma) protected
References debug_.
Referenced by getGain().
getBeta()
double UwElectroMagneticMPropagation::getBeta (double * rel_e, double w, double sigma) protected
References debug_.
Referenced by getGain().
getEtaW()
void UwElectroMagneticMPropagation::getEtaW (double * etaW, double * rel_e, double w, double sigma) protected
References debug_.
Referenced by getGain().
getGain()
double UwElectroMagneticMPropagation::getGain (Packet * p) virtual
Calculate the gain of the transmission (attenuation)
Parameters
Packet* Pointer to the packet that has to be received.
Returns
the gain due to the electromagnetic propagation.
References debug_, getAlpha(), getBeta(), getEtaW(), getModTauSquared(), and getRelativePermittivity().
getModTauSquared()
double UwElectroMagneticMPropagation::getModTauSquared (double * etaW) protected
References debug_.
Referenced by getGain().
getRelativePermittivity()
void UwElectroMagneticMPropagation::getRelativePermittivity (double f_, double * rel_e) protected
References debug_, getSigmaSW(), S_, and T_.
Referenced by getGain().
getSigmaSW()
double UwElectroMagneticMPropagation::getSigmaSW () protected
References S_, and T_.
Referenced by getRelativePermittivity().
Member Data Documentation
debug_
int UwElectroMagneticMPropagation::debug_
Referenced by getAlpha(), getBeta(), getEtaW(), getGain(), getModTauSquared(), getRelativePermittivity(), and UwElectroMagneticMPropagation().
S_
double UwElectroMagneticMPropagation::S_ protected
Salinity [(g/kg)^2]
Referenced by command(), getRelativePermittivity(), getSigmaSW(), and UwElectroMagneticMPropagation().
T_
double UwElectroMagneticMPropagation::T_ protected
Temperature [°C]
Referenced by command(), getRelativePermittivity(), getSigmaSW(), and UwElectroMagneticMPropagation().
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/propagation/uwem_propagation/uwem-mpropagation.h
DESERT_Framework/DESERT/propagation/uwem_propagation/uwem-mpropagation.cpp