DESERT: RxFrameSetKey Class Reference
RxFrameSetKey Class Reference
#include <frame-set.h>
Public Member Functions
RxFrameSetKey (uint8_t, unsigned int)
~RxFrameSetKey ()
uint8_t srcID () const
unsigned int pktID () const
bool operator< (RxFrameSetKey) const
std::string displayKey () const
Private Attributes
uint8_t srcID_
unsigned int pktID_
Constructor & Destructor Documentation
RxFrameSetKey()
RxFrameSetKey::RxFrameSetKey (uint8_t srcID, unsigned int pktID)
References pktID(), pktID_, srcID(), and srcID_.
~RxFrameSetKey()
RxFrameSetKey::~RxFrameSetKey ()
Member Function Documentation
displayKey()
std::string RxFrameSetKey::displayKey () const
References pktID_, and srcID_.
operator<()
bool RxFrameSetKey::operator< (RxFrameSetKey key2) const
References pktID_, and srcID_.
pktID()
unsigned int RxFrameSetKey::pktID () const inline
Return the pktID_ variable.
References pktID_.
Referenced by RxFrameSetKey().
srcID()
uint8_t RxFrameSetKey::srcID () const inline
Return the srcID_ variable.
References srcID_.
Referenced by RxFrameSetKey().
Member Data Documentation
pktID_
unsigned int RxFrameSetKey::pktID_ private
ID of the packet.
Referenced by displayKey(), operator<(), pktID(), and RxFrameSetKey().
srcID_
uint8_t RxFrameSetKey::srcID_ private
ID of the packet's source node.
Referenced by displayKey(), operator<(), RxFrameSetKey(), and srcID().
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/physical/uw-al/frame-set.h
DESERT_Framework/DESERT/physical/uw-al/frame-set.cpp