DESERT: UnderwaterPhysicalfromdb Class Reference
UnderwaterPhysicalfromdb Class Reference
#include <uwphysicalfromdb.h>
Public Member Functions
UnderwaterPhysicalfromdb ()
virtual ~UnderwaterPhysicalfromdb ()
virtual int command (int, const char *const *)
Public Member Functions inherited from UnderwaterGainFromDb
UnderwaterGainFromDb ()
virtual ~UnderwaterGainFromDb ()
Public Member Functions inherited from UnderwaterPhysical
UnderwaterPhysical ()
virtual ~UnderwaterPhysical ()
virtual void recv (Packet *) override
int recvSyncClMsg (ClMessage *m) override
Protected Member Functions
virtual double getPER (double _snr, int _nbits, Packet *p)
virtual double getGain (const double &_time, const double &_source_depth, const double &_destination_depth, const double &_destination_distance)
virtual double getSelfInterference (const double &_time, const double &_source_depth, const double &_destination_depth, const double &_destination_distance)
virtual string createNameFile (const char *_path, const int &_time, const int &_source_depth, const int &_tau_index)
virtual double retrieveFromFile (const string &_file_name, const int &_row_index, const int &_column_index) const
void setTauIndex (const int &_tau_index)
const int & getTauIndex () const
Protected Member Functions inherited from UnderwaterGainFromDb
virtual void setTimeRoughness (const int &)
virtual void setDepthRoughness (const int &)
virtual void setDistanceRoughness (const int &)
virtual void setTotalTime (const int &)
virtual void setFrequencyCorrectionFactor (const double &)
const int & getTimeRoughness () const
const int & getDepthRoughness () const
const int & getDistanceRoughness () const
const int & getTotalTime () const
const double & getFrequencyCorrectionFactor () const
virtual double retriveGainFromFile (const string &, const int &, const int &) const
virtual string createNameFile (const int &, const int &)
const bool isZero (const double &value) const
Protected Member Functions inherited from UnderwaterPhysical
virtual void updateInstantaneousStats ()
virtual void endTx (Packet *p) override
virtual void endRx (Packet *p) override
virtual void startRx (Packet *p) override
virtual double consumedEnergyTx (const double &_duration) const
virtual double consumedEnergyRx (const double &_duration) const
bool isZero (const double &value) const
double Get_Tx_Time () const
double Get_Rx_Time () const
double Get_Energy_Tx () const
double Get_Energy_Rx () const
double Get_Transmitted_bytes () const
void incrTot_pkts_lost ()
void incrTotCrtl_pkts_lost ()
void incrErrorCtrlPktsInterf ()
void incrCollisionDATAvsCTRL ()
void incrCollisionCTRL ()
void incrCollisionDATA ()
int getTot_pkts_lost () const
int getTot_CtrlPkts_lost () const
int getError_CtrlPktsInterf () const
int getCollisionsDATAvsCTRL () const
int getCollisionsCTRL () const
int getCollisionsDATA () const
double log2 (const double &_input) const
double get_prob_error_symbol_mpsk (const double &_snr, const uint32_t _M) const
Private Attributes
char * path_gainmaps
char * path_selfinterference
int tau_index
Additional Inherited Members
Protected Attributes inherited from UnderwaterGainFromDb
char * path_
char token_separator_
ostringstream osstream_
Protected Attributes inherited from UnderwaterPhysical
std::string modulation_name_
double time_ready_to_end_rx_
double Tx_Time_
double Rx_Time_
double Energy_Tx_
double Energy_Rx_
double Transmitted_bytes_
double tx_power_
double rx_power_
int tot_pkts_lost
int tot_ctrl_pkts_lost
int errorCtrlPktsInterf
int collisionDataCTRL
int collisionCTRL
int collisionDATA
std::string Interference_Model
uwinterference * interference_
Constructor & Destructor Documentation
UnderwaterPhysicalfromdb()
UnderwaterPhysicalfromdb::UnderwaterPhysicalfromdb ()
Constructor of UnderwaterMPhyBpskDb class.
References path_gainmaps, path_selfinterference, and tau_index.
~UnderwaterPhysicalfromdb()
virtual UnderwaterPhysicalfromdb::~UnderwaterPhysicalfromdb () inline virtual
Destructor of UnderwaterMPhyBpskDb class.
Member Function Documentation
command()
int UnderwaterPhysicalfromdb::command (int argc, const char *const * argv) virtual
TCL command interpreter. It implements the following OTcl methods:
Parameters
argc Number of arguments in argv.
argv Array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not.
Reimplemented from UnderwaterGainFromDb.
References UnderwaterGainFromDb::command(), UnderwaterGainFromDb::path_, path_gainmaps, and path_selfinterference.
createNameFile()
string UnderwaterPhysicalfromdb::createNameFile (const char * _path, const int & _time, const int & _source_depth, const int & _tau_index) protected virtual
Create the name of the file to read.
Parameters
_time Timestamp (in s)
_source_depth Source depth (in m)
_destination_depth Destination depth (in m)
_destination_distance Destination distance (in m)
References UnderwaterGainFromDb::osstream_.
Referenced by getGain(), and getSelfInterference().
getGain()
double UnderwaterPhysicalfromdb::getGain (const double & _time, const double & _source_depth, const double & _destination_depth, const double & _destination_distance) protected virtual
Read from the gain.
Parameters
_time Timestamp (in s)
_source_depth Source depth (in m)
_destination_depth Destination depth (in m)
_destination_distance Destination distance (in m)
Returns
Gain in dB.
Reimplemented from UnderwaterGainFromDb.
References createNameFile(), UnderwaterGainFromDb::getDepthRoughness(), UnderwaterGainFromDb::getDistanceRoughness(), getTauIndex(), UnderwaterGainFromDb::getTimeRoughness(), UnderwaterGainFromDb::getTotalTime(), path_gainmaps, and retrieveFromFile().
Referenced by getPER().
getPER()
double UnderwaterPhysicalfromdb::getPER (double _snr, int _nbits, Packet * p) protected virtual
Return the Packet Error Rate of the packet p passed as input.
Parameters
_snr Not used
_nbits Length of the packet
p Packet
Returns
Packet Error Rate of the packet p
Reimplemented from UnderwaterGainFromDb.
References getGain(), UnderwaterPhysical::getPER(), and getSelfInterference().
getSelfInterference()
double UnderwaterPhysicalfromdb::getSelfInterference (const double & _time, const double & _source_depth, const double & _destination_depth, const double & _destination_distance) protected virtual
Read from the self interference.
Parameters
_time Timestamp (in s)
_source_depth Source depth (in m)
_destination_depth Destination depth (in m)
_destination_distance Destination distance (in m)
Returns
Self Interference in dB.
References createNameFile(), UnderwaterGainFromDb::getDepthRoughness(), UnderwaterGainFromDb::getDistanceRoughness(), getTauIndex(), UnderwaterGainFromDb::getTimeRoughness(), UnderwaterGainFromDb::getTotalTime(), path_selfinterference, and retrieveFromFile().
Referenced by getPER().
getTauIndex()
const int & UnderwaterPhysicalfromdb::getTauIndex () const inline protected
Return the value of the tau_index parameter.
Returns
tau_index
References tau_index.
Referenced by getGain(), and getSelfInterference().
retrieveFromFile()
double UnderwaterPhysicalfromdb::retrieveFromFile (const string & _file_name, const int & _row_index, const int & _column_index) const protected virtual
Read from a file the value in a specific row - column.
Parameters
_file_name name of the file
_row_index index of the row
_column_index index of the column
Returns
the value read
References UnderwaterGainFromDb::isZero(), and UnderwaterGainFromDb::token_separator_.
Referenced by getGain(), and getSelfInterference().
setTauIndex()
void UnderwaterPhysicalfromdb::setTauIndex (const int & _tau_index) inline protected
Set the line_index parameter.
Parameters
Line index to load in the file
References tau_index.
Member Data Documentation
path_gainmaps
char* UnderwaterPhysicalfromdb::path_gainmaps private
Name of the trace file writter for the current node.
Referenced by command(), getGain(), and UnderwaterPhysicalfromdb().
path_selfinterference
char* UnderwaterPhysicalfromdb::path_selfinterference private
Name of the trace file writter for the current node.
Referenced by command(), getSelfInterference(), and UnderwaterPhysicalfromdb().
tau_index
int UnderwaterPhysicalfromdb::tau_index private
Tau index to load in the file.
Referenced by getTauIndex(), setTauIndex(), and UnderwaterPhysicalfromdb().
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/physical/uwphysicalfromdb/uwphysicalfromdb.h
DESERT_Framework/DESERT/physical/uwphysicalfromdb/uwphysicalfromdb.cpp