DESERT: UwSCTrackerModule Class Reference
UwSCTrackerModule Class Reference
#include <uwsc-tracker-module.h>
Public Member Functions
UwSCTrackerModule ()
virtual ~UwSCTrackerModule ()=default
virtual int command (int argc, const char *const *argv) override
virtual void recv (Packet *) override
Public Member Functions inherited from UwTrackerModule
UwTrackerModule ()
UwTrackerModule (UWSMPosition *p)
virtual ~UwTrackerModule ()
virtual void initPkt (Packet *p)
Public Member Functions inherited from UwCbrModule
UwCbrModule ()
virtual ~UwCbrModule ()=default
virtual void recv (Packet *p, Handler *h) override
virtual double GetRTT () const
virtual double GetFTT () const
virtual double GetTxTime () const
virtual double GetPER () const
virtual double GetTHR () const
virtual double GetRTTstd () const
virtual double GetFTTstd () const
virtual void resetStats ()
void printIdsPkts () const
Protected Attributes
int leader_id
std::list< Position > tracked_mines
Protected Attributes inherited from UwTrackerModule
UWSMPosition * track_position
hdr_uwTracker track_measure
double max_tracking_distance
int send_only_active_trace
int track_my_position
double tracking_period
UwUpdateTrackMeasure measure_timer
Protected Attributes inherited from UwCbrModule
uint16_t dstPort_
std::string log_suffix
nsaddr_t dstAddr_
char priority_
std::ofstream tracefile
std::string tracefilename
bool * sn_check
int PoissonTraffic_
int debug_
int drop_out_of_order_
uint traffic_type_
UwSendTimer sendTmr_
int txsn
int hrsn
int pkts_recv
int pkts_ooseq
int pkts_lost
int pkts_invalid
int pkts_last_reset
int cnt
double rftt
double srtt
double sftt
double lrtime
double sthr
double period_
int pktSize_
double sumrtt
double sumrtt2
int rttsamples
double sumftt
double sumftt2
int fttsamples
double sumtxtimes = 0
double sumbytes
double sumdt
uint32_t esn
int tracefile_enabler_
Additional Inherited Members
Protected Member Functions inherited from UwTrackerModule
virtual void printReceivedPacket (Packet *p)
void sendPkt ()
void updateTrackMeasure ()
virtual void start ()
virtual void stop ()
Protected Member Functions inherited from UwCbrModule
virtual void sendPktLowPriority ()
virtual void sendPktHighPriority ()
virtual void transmit ()
virtual void updateRTT (const double &)
virtual void updateFTT (const double &)
virtual void updateThroughput (const int &, const double &)
virtual void incrPktLost (const int &)
virtual void incrPktRecv ()
virtual void incrPktOoseq ()
virtual void incrPktInvalid ()
virtual double getTimeBeforeNextPkt ()
Static Protected Member Functions inherited from UwCbrModule
static int getCbrHeaderSize ()
Static Protected Attributes inherited from UwCbrModule
static int uidcnt_ = 0
Detailed Description
UwSCTrackerModule class adds to the UwTrackerModule class the possibility to send cross layer messages.
Constructor & Destructor Documentation
UwSCTrackerModule()
UwSCTrackerModule::UwSCTrackerModule ()
Default Constructor of UwSCTrackerModule class.
~UwSCTrackerModule()
virtual UwSCTrackerModule::~UwSCTrackerModule () virtual default
Destructor of UwSCTrackerModule class.
Member Function Documentation
command()
int UwSCTrackerModule::command (int argc, const char *const * argv) override virtual
TCL command interpreter. It implements the following OTcl methods:
Parameters
argc Number of arguments in argv.
argv Array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not.
Reimplemented from UwTrackerModule.
References UwTrackerModule::command(), and leader_id.
recv()
void UwSCTrackerModule::recv (Packet * p) override virtual
Performs the reception of packets from upper and lower layers.
Parameters
Packet* Pointer to the packet will be received.
Reimplemented from UwCbrModule.
References UwCbrModule::debug_, leader_id, hdr_uwSCFTracker::mine_remove(), UwCbrModule::recv(), ClMsgTrack2McStatus::setMineStatus(), ClMsgTrack2McPosition::setTrackPosition(), tracked_mines, hdr_uwSCFTracker::x(), hdr_uwSCFTracker::y(), and hdr_uwSCFTracker::z().
Member Data Documentation
leader_id
int UwSCTrackerModule::leader_id protected
ID of the Tracker leader.
Referenced by command(), and recv().
tracked_mines
std::list<Position> UwSCTrackerModule::tracked_mines protected
Positions of the mines tracked by the follower.
Referenced by recv().
The documentation for this class was generated from the following files:
DESERT_Addons/uwswarm_control/uwsc-tracker-module.h
DESERT_Addons/uwswarm_control/uwsc-tracker-module.cc