DESERT: WossGroupMob3D::UpdatePositionTimer Class Reference
WossGroupMob3D::UpdatePositionTimer Class Reference
#include <woss-groupmobility-3d.h>
Public Member Functions
UpdatePositionTimer (WossGroupMob3D *mo)
virtual ~UpdatePositionTimer ()
virtual void schedule (double val)
Protected Member Functions
virtual void expire (Event *e)
Protected Attributes
WossGroupMob3D * mod
Detailed Description
Base class of UpdateTimerPosition class which is inherited from TimerHandler class.
Constructor & Destructor Documentation
UpdatePositionTimer()
WossGroupMob3D::UpdatePositionTimer::UpdatePositionTimer (WossGroupMob3D * mo) inline
Constructor of UpdateTimerPosition class
References mod.
~UpdatePositionTimer()
virtual WossGroupMob3D::UpdatePositionTimer::~UpdatePositionTimer () inline virtual
Destructor of UpdateTimerPosition class
Member Function Documentation
expire()
void WossGroupMob3D::UpdatePositionTimer::expire (Event * e) protected virtual
This method tell the node what to do when update timer expire.
References WossGroupMob3D::maddr, mod, WossGroupMob3D::update(), and WossGroupMob3D::wossgroup_debug_.
schedule()
virtual void WossGroupMob3D::UpdatePositionTimer::schedule (double val) inline virtual
Update Time is scheduled using this method.
Referenced by WossGroupMob3D::update(), and WossGroupMob3D::WossGroupMob3D().
Member Data Documentation
mod
WossGroupMob3D* WossGroupMob3D::UpdatePositionTimer::mod protected
An Object pointer of WossGroupMob3D class.
Referenced by expire(), and UpdatePositionTimer().
The documentation for this class was generated from the following files:
DESERT_Addons/wossgroupmob3D/woss-groupmobility-3d.h
DESERT_Addons/wossgroupmob3D/woss-groupmobility-3d.cpp