DESERT: MsgDisplayer Class Reference
MsgDisplayer Class Reference
#include <msg-display.h>
Public Member Functions
MsgDisplayer ()
MsgDisplayer (int n, std::string pn, int pactive)
~MsgDisplayer ()
void initDisplayer (int n, std::string pn, int pactive)
void printStatus (std::string st, std::string fxName, double now, int addr)
Private Attributes
int nodeNum
std::string protocolName
int printActive
Constructor & Destructor Documentation
MsgDisplayer() [1/2]
MsgDisplayer::MsgDisplayer ()
MsgDisplayer() [2/2]
MsgDisplayer::MsgDisplayer (int n, std::string pn, int pactive)
References nodeNum, printActive, and protocolName.
~MsgDisplayer()
MsgDisplayer::~MsgDisplayer ()
Member Function Documentation
initDisplayer()
void MsgDisplayer::initDisplayer (int n, std::string pn, int pactive)
References nodeNum, printActive, and protocolName.
Referenced by UwOFDMPhy::init_ofdm_node(), and UWSmartOFDM::UWSmartOFDM().
printStatus()
void MsgDisplayer::printStatus (std::string st, std::string fxName, double now, int addr)
References printActive, and protocolName.
Referenced by UwOFDMPhy::endRx(), UwOFDMPhy::getTxDuration(), UwOFDMPhy::init_ofdm_node(), UWSmartOFDM::Mac2PhyStartTx(), UWSmartOFDM::matchCarriers(), UWSmartOFDM::Phy2MacEndRx(), UWSmartOFDM::Phy2MacEndTx(), UwOFDMPhy::recv(), UWSmartOFDM::recvFromUpperLayers(), UwOFDMPhy::startRx(), UWSmartOFDM::stateBackoff(), UWSmartOFDM::stateBackoffCTS(), UWSmartOFDM::stateCheckAckExpired(), UWSmartOFDM::stateCheckBackoffExpired(), UWSmartOFDM::stateCheckCTSBackoffExpired(), UWSmartOFDM::stateIdle(), UWSmartOFDM::stateRxAck(), UWSmartOFDM::stateRxCTS(), UWSmartOFDM::stateRxData(), UWSmartOFDM::stateRxRTS(), UWSmartOFDM::stateSendCTS(), UWSmartOFDM::stateSendRTS(), UWSmartOFDM::stateTxAck(), UWSmartOFDM::stateTxData(), UWSmartOFDM::stateWaitAck(), UWSmartOFDM::stateWaitCTS(), UWSmartOFDM::stateWaitData(), UWSmartOFDM::txCTS(), UWSmartOFDM::txRTS(), and UWSmartOFDM::updateInterfTable().
Member Data Documentation
nodeNum
int MsgDisplayer::nodeNum private
Referenced by initDisplayer(), and MsgDisplayer().
printActive
int MsgDisplayer::printActive private
Referenced by initDisplayer(), MsgDisplayer(), and printStatus().
protocolName
std::string MsgDisplayer::protocolName private
Referenced by initDisplayer(), MsgDisplayer(), and printStatus().
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/utility/msg-display/msg-display.h
DESERT_Framework/DESERT/utility/msg-display/msg-display.cpp