DESERT: UwMultiTrafficControl Class Reference
UwMultiTrafficControl Class Reference
#include <uwmulti-traffic-control.h>
Public Member Functions
UwMultiTrafficControl ()
virtual ~UwMultiTrafficControl ()
virtual int command (int, const char *const *)
virtual void recv (Packet *p)
Protected Member Functions
virtual void recvFromUpperLayers (Packet *p)
virtual void manageBuffer (int traffic)
virtual void insertInBuffer (Packet *p, int traffic)
virtual Packet * removeFromBuffer (int traffic)
virtual Packet * getFromBuffer (int traffic)
void insertTraffic2UpLayer (int traffic, int upper_layer_id)
void insertTraffic2LowerLayer (int traffic, int lower_layer_stack, int lower_layer_id, int behavior)
virtual int getBestLowerLayer (int traffic, Packet *p=NULL)
virtual int getUpperLayer (int traffic)
virtual void eraseTraffic2LowerLayer (int traffic, int lower_layer_stack)
virtual void eraseTraffic2Low (int traffic)
virtual void eraseTraffic2Up (int traffic)
virtual bool addUpLayerFromTag (int traffic_id, const std::string &tag)
virtual bool addLowLayerFromTag (int traffic_id, const std::string &tag, int behavior)
void setBufferFeature (int traffic_id, int max_size, bool is_circular, double send_down_delay=0)
virtual void incrPktLoss (int traffic_id)
virtual uint getDiscardedPacket (int traffic_id) const
Protected Attributes
int debug_
UpTrafficMap up_map
DownTrafficMap down_map
DownTrafficBuffer down_buffer
BufferTrafficFeature buffer_feature_map
Detailed Description
Class used to represents the UwMultiTrafficControl layer of a node.
Constructor & Destructor Documentation
UwMultiTrafficControl()
UwMultiTrafficControl::UwMultiTrafficControl ()
Constructor of UwMultiPhy class.
References debug_.
~UwMultiTrafficControl()
virtual UwMultiTrafficControl::~UwMultiTrafficControl () inline virtual
Destructor of UwMultiPhy class.
Member Function Documentation
addLowLayerFromTag()
bool UwMultiTrafficControl::addLowLayerFromTag (int traffic_id, const std::string & tag, int behavior) protected virtual
add a lower layer from the tag name in the map
Parameters
traffic application traffic id
tag tag of the lower module
behavior behavior of the layer
Returns
true if there is a valid layer associated to tag, false otherwise.
References debug_, and insertTraffic2LowerLayer().
Referenced by command(), and UwMultiTrafficRangeCtr::command().
addUpLayerFromTag()
bool UwMultiTrafficControl::addUpLayerFromTag (int traffic_id, const std::string & tag) protected virtual
add an upper layer from the tag name in the map
Parameters
traffic application traffic id
tag tag of the upper module
Returns
true if there is a valid layer associated to tag, false otherwise.
References debug_, and insertTraffic2UpLayer().
Referenced by command().
command()
int UwMultiTrafficControl::command (int argc, const char *const * argv) virtual
TCL command interpreter. It implements the following OTcl methods:
Parameters
argc Number of arguments in argv.
argv Array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not.
Reimplemented in UwMultiTrafficRangeCtr.
References addLowLayerFromTag(), addUpLayerFromTag(), getDiscardedPacket(), and setBufferFeature().
Referenced by UwMultiTrafficRangeCtr::command().
eraseTraffic2Low()
void UwMultiTrafficControl::eraseTraffic2Low (int traffic) protected virtual
remove the traffic from the lower layers matrix
Parameters
traffic application traffic id
References up_map.
eraseTraffic2LowerLayer()
void UwMultiTrafficControl::eraseTraffic2LowerLayer (int traffic, int lower_layer_stack) protected virtual
remove the behavior from the traffic lower layers matrix
Parameters
traffic application traffic id
lower_layer_stack lower layer stack id
References down_map.
eraseTraffic2Up()
void UwMultiTrafficControl::eraseTraffic2Up (int traffic) protected virtual
remove the traffic from the upper layers matrix
Parameters
traffic application traffic id
References up_map.
getBestLowerLayer()
int UwMultiTrafficControl::getBestLowerLayer (int traffic, Packet * p = NULL) protected virtual
return the Best Lower Layer id where to forward the packet of traffic type
Parameters
traffic application traffic id
Returns
the layer id
Reimplemented in UwMultiTrafficRangeCtr.
References debug_, and down_map.
Referenced by manageBuffer().
getDiscardedPacket()
uint UwMultiTrafficControl::getDiscardedPacket (int traffic_id) const protected virtual
get discarded packets
Parameters
traffic_id application traffic id
Returns
number of discarded packets for the given traffic id buffer)
References buffer_feature_map.
Referenced by command().
getFromBuffer()
Packet * UwMultiTrafficControl::getFromBuffer (int traffic) protected virtual
get a packet of a certain type from the buffer and return it
Parameters
traffic application traffic id
Returns
the pointer of the removed packet
References debug_, and down_buffer.
Referenced by UwMultiTrafficRangeCtr::manageBuffer(), UwMultiTrafficRangeCtr::manageCheckedLayer(), and UwMultiTrafficRangeCtr::timerExpired().
getUpperLayer()
int UwMultiTrafficControl::getUpperLayer (int traffic) protected virtual
return the Upper Layer id where to forward the received packet of traffic type
Parameters
traffic application traffic id
Returns
the layer id
References debug_, and up_map.
Referenced by recv().
incrPktLoss()
void UwMultiTrafficControl::incrPktLoss (int traffic_id) protected virtual
Increment by 1 the number of lost packets for the given traffic
Parameters
traffic_id application traffic id
References buffer_feature_map.
Referenced by insertInBuffer().
insertInBuffer()
void UwMultiTrafficControl::insertInBuffer (Packet * p, int traffic) protected virtual
insert a packet of a certain type in the buffer
Parameters
p pointer of the packet
traffic application traffic id
References buffer_feature_map, BufferType::CIRCULAR, debug_, down_buffer, incrPktLoss(), and q.
Referenced by UwMultiTrafficRangeCtr::manageCheckedLayer(), and recvFromUpperLayers().
insertTraffic2LowerLayer()
void UwMultiTrafficControl::insertTraffic2LowerLayer (int traffic, int lower_layer_stack, int lower_layer_id, int behavior) inline protected
Set to which upper layer forward a specific kind of traffic received from the lower layers
Parameters
application traffic id
lower_layer_stack unique identifier of the lower layer stack
check_range if TRUE follows the CHECK_RANGE behavior, else the ROBUST one
References down_map.
Referenced by addLowLayerFromTag().
insertTraffic2UpLayer()
void UwMultiTrafficControl::insertTraffic2UpLayer (int traffic, int upper_layer_id) inline protected
Set to which upper layer forward a specific kind of traffic received from the lower layers
Parameters
traffic application traffic id
upper_layer_id unique identifier of the upper layer id
References up_map.
Referenced by addUpLayerFromTag().
manageBuffer()
void UwMultiTrafficControl::manageBuffer (int traffic) protected virtual
manage to tx a packet of traffic type
Parameters
traffic application traffic id
Reimplemented in UwMultiTrafficRangeCtr.
References buffer_feature_map, debug_, down_buffer, getBestLowerLayer(), and removeFromBuffer().
Referenced by recvFromUpperLayers().
recv()
void UwMultiTrafficControl::recv (Packet * p) virtual
recv method. It is called when a packet is received from the other layers
Parameters
Packet* Pointer to the packet that are going to be received
References debug_, getUpperLayer(), recvFromUpperLayers(), and hdr_uwcbr::traffic_type().
Referenced by UwMultiTrafficRangeCtr::recv().
recvFromUpperLayers()
void UwMultiTrafficControl::recvFromUpperLayers (Packet * p) protected virtual
Handle a packet coming from upper layers
Parameters
p pointer to the packet
References debug_, insertInBuffer(), manageBuffer(), and hdr_uwcbr::traffic_type().
Referenced by recv().
removeFromBuffer()
Packet * UwMultiTrafficControl::removeFromBuffer (int traffic) protected virtual
remove a packet of a certain type from the buffer and return it
Parameters
traffic application traffic id
Returns
the pointer of the removed packet
References debug_, and down_buffer.
Referenced by manageBuffer(), UwMultiTrafficRangeCtr::manageBuffer(), and UwMultiTrafficRangeCtr::manageCheckedLayer().
setBufferFeature()
void UwMultiTrafficControl::setBufferFeature (int traffic_id, int max_size, bool is_circular, double send_down_delay = 0) protected
set buffer features for the given traffic type
Parameters
traffic_id application traffic id
max_size maximum buffer size
is_circular true if buffer is circular, false otherwise (discard new) buffer)
send_down_delay delay used to send down packets
References buffer_feature_map, BufferType::CIRCULAR, debug_, and BufferType::DISCARD_INCOMING.
Referenced by command().
Member Data Documentation
buffer_feature_map
BufferTrafficFeature UwMultiTrafficControl::buffer_feature_map protected
Map with features of each buffer
Referenced by getDiscardedPacket(), incrPktLoss(), insertInBuffer(), manageBuffer(), UwMultiTrafficRangeCtr::manageBuffer(), UwMultiTrafficRangeCtr::manageCheckedLayer(), and setBufferFeature().
debug_
int UwMultiTrafficControl::debug_ protected
Flag to activate debug verbosity.
Referenced by addLowLayerFromTag(), addUpLayerFromTag(), UwMultiTrafficRangeCtr::checkRange(), getBestLowerLayer(), UwMultiTrafficRangeCtr::getBestLowerLayer(), getFromBuffer(), getUpperLayer(), insertInBuffer(), manageBuffer(), UwMultiTrafficRangeCtr::manageCheckedLayer(), recv(), UwMultiTrafficRangeCtr::recv(), recvFromUpperLayers(), removeFromBuffer(), setBufferFeature(), UwMultiTrafficRangeCtr::timerExpired(), and UwMultiTrafficControl().
down_buffer
DownTrafficBuffer UwMultiTrafficControl::down_buffer protected
Map of buffer per traffic types
Referenced by getFromBuffer(), insertInBuffer(), manageBuffer(), and removeFromBuffer().
down_map
DownTrafficMap UwMultiTrafficControl::down_map protected
Map of lower layers.
Referenced by eraseTraffic2LowerLayer(), getBestLowerLayer(), UwMultiTrafficRangeCtr::getBestLowerLayer(), and insertTraffic2LowerLayer().
up_map
UpTrafficMap UwMultiTrafficControl::up_map protected
Map of upper layers.
Referenced by eraseTraffic2Low(), eraseTraffic2Up(), getUpperLayer(), and insertTraffic2UpLayer().
The documentation for this class was generated from the following files:
DESERT_Addons/uwmulti_traffic_control/uwmulti-traffic-control.h
DESERT_Addons/uwmulti_traffic_control/uwmulti-traffic-control.cc