DESERT: UwEvoLogicsS2CModem Class Reference
UwEvoLogicsS2CModem Class Reference
#include <uwevologicss2cmodem.h>
Public Types
enum class TransmissionMode { BURST = 0 , IM = 1 }
enum class TransmissionState { TX_IDLE = 0 , TX_PENDING }
Public Types inherited from UwModem
enum class LogLevel { ERROR = 0 , INFO = 1 , DEBUG = 2 }
Public Member Functions
UwEvoLogicsS2CModem ()
virtual ~UwEvoLogicsS2CModem ()
virtual void recv (Packet *p)
virtual int command (int argc, const char *const *argv)
virtual int recvSyncClMsg (ClMessage *m)
virtual double getTxDuration (Packet *p)
virtual bool configure (Config cmd)
virtual void initializeLUT ()
Public Member Functions inherited from UwModem
UwModem ()
virtual ~UwModem ()
virtual int getModulationType (Packet *P)
void setModemID (int ID)
int getModemID ()
void printOnLog (LogLevel log_level, string module, string message)
LogLevel getLogLevel ()
int getDebug ()
std::string getLogFile ()
void realTxEnded (Packet *p)
Private Types
enum class Config {
ATL_GET , ATL_SET , ATAL_GET , ATAL_SET ,
MODEM_STATUS , CURR_SETTINGS , UNKNOWN
}
Private Member Functions
virtual void startTx (Packet *p)
virtual void startRx (Packet *p)
virtual void endRx (Packet *p)
virtual void start ()
virtual void stop ()
virtual void transmittingData ()
virtual void receivingData ()
void updateStatus (UwInterpreterS2C::Response cmd)
void setFailedTx (Packet *p)
void createRxPacket (Packet *p)
Private Attributes
std::unique_ptr< UwConnector > p_connector
std::unique_ptr< UwInterpreterS2C > p_interpreter
ModemState status
TransmissionState tx_status
std::mutex status_m
std::mutex tx_status_m
std::mutex tx_queue_m
std::condition_variable status_cv
std::condition_variable tx_status_cv
std::condition_variable tx_queue_cv
std::atomic< bool > receiving
std::atomic< bool > transmitting
std::atomic< bool > im_status_updated
std::thread rx_thread
std::thread tx_thread
std::string rx_payload
TransmissionMode tx_mode
bool ack_mode
double virtual_time_ref
int curr_source_level
int n_rx_failed
int pend_source_level
bool source_level_change
TransmissionDurationLUT size2dur_
std::string txdur_file_name_
char txdur_token_separator_
bool initLUT_
Static Private Attributes
static const std::chrono::milliseconds MODEM_TIMEOUT
static const std::chrono::milliseconds WAIT_DELIVERY_IM
static const std::chrono::seconds WAIT_DELIVERY_BURST
static const double EPSILON_S
static uint MAX_N_STATUS_QUERIES = 10
Additional Inherited Members
Static Public Member Functions inherited from UwModem
static bool string2log (const std::string &ll_string, LogLevel &ll)
static bool log2string (LogLevel ll, std::string &ll_string)
Protected Member Functions inherited from UwModem
virtual void endTx (Packet *p)
void checkEvent ()
Protected Attributes inherited from UwModem
int modemID
std::vector< char > data_buffer
std::queue< Packet * > tx_queue
std::queue< Packet * > rx_queue
unsigned int DATA_BUFFER_LEN
int MAX_READ_BYTES
std::string modem_address
int debug_
std::ofstream outLog
std::string logFile
std::string log_suffix
LogLevel loglevel_
bool log_is_open
CheckTimer * checkTimer
double period
std::queue< ModemEvent > event_q
Member Enumeration Documentation
Config
enum class UwEvoLogicsS2CModem::Config strong private
Enum listing the availbale configuration settings. See the EvoLogics S2C manuals or reach for www.evologics.de
Enumerator
ATL_GET
ATL_SET
ATAL_GET
ATAL_SET
MODEM_STATUS
CURR_SETTINGS
UNKNOWN
TransmissionMode
enum class UwEvoLogicsS2CModem::TransmissionMode strong
Transmission mode: either IM or BURST See the EvoLogics S2C manuals or reach for www.evologics.de
Enumerator
BURST
IM
TransmissionState
enum class UwEvoLogicsS2CModem::TransmissionState strong
Transmission state: controls the flow of execution for sending commands to the S2C device
Enumerator
TX_IDLE
TX_PENDING
Constructor & Destructor Documentation
UwEvoLogicsS2CModem()
UwEvoLogicsS2CModem::UwEvoLogicsS2CModem ()
Constructor of the UwEvoLogicsS2CModem class
Parameters
address string containing the address to connect to
buflen lenght in char of the data buffer
read len length in char of a signle read from the connector
References UwModem::DATA_BUFFER_LEN, MAX_N_STATUS_QUERIES, and UwModem::MAX_READ_BYTES.
~UwEvoLogicsS2CModem()
UwEvoLogicsS2CModem::~UwEvoLogicsS2CModem () virtual
Destructor of the UwEvoLogicsS2CModem class
References stop().
Member Function Documentation
command()
int UwEvoLogicsS2CModem::command (int argc, const char *const * argv) virtual
Tcl command interpreter: Method that maps Tcl commands into C++ methods.
Parameters
argc number of arguments in argv
argv array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not
Reimplemented from UwModem.
References ack_mode, BURST, UwModem::command(), IM, initializeLUT(), p_connector, p_interpreter, start(), stop(), tx_mode, txdur_file_name_, and txdur_token_separator_.
Referenced by configure().
configure()
bool UwEvoLogicsS2CModem::configure (Config cmd) virtual
Method that sends a written configuration the the EvoLgoics modem. The configuration string could be a request of configurations (the AT commands conaining '?') or a setting command (the AT commands containing '!').
Parameters
command the command string complying with the device format requirements.
Returns
boolean true if the command was correctly sent to the device
References ATAL_GET, ATAL_SET, ATL_GET, ATL_SET, BUSY, command(), CURR_SETTINGS, UwModem::ERROR, MODEM_STATUS, MODEM_TIMEOUT, UwModem::modemID, p_connector, p_interpreter, pend_source_level, UwModem::printOnLog(), status, status_cv, status_m, TX_PENDING, tx_status, and tx_status_m.
createRxPacket()
void UwEvoLogicsS2CModem::createRxPacket (Packet * p) private
Method that fills up a packet with the needed header and payload and makes it ready to be sent to the layer above
Parameters
p instance of an empty packet to be filled
References hdr_uwal::binPkt(), hdr_uwal::binPktLength(), and rx_payload.
Referenced by updateStatus().
endRx()
void UwEvoLogicsS2CModem::endRx (Packet * p) private virtual
Method that ends a packet reception. This method is also in charge of sending the received NS-MIRACLE packet to the upper layers
Parameters
p Packet pointer to the packet being sent
Implements UwModem.
References UwModem::INFO, and UwModem::printOnLog().
Referenced by recv().
getTxDuration()
double UwEvoLogicsS2CModem::getTxDuration (Packet * p) virtual
Method that return the duration of a given transmitted packet. Inherited from MPhy, in NS-MIRACLE, could be empty if there is no way to retrieve this information.
Parameters
p Packet pointer to the given packet being transmitted
Returns
duration in seconds
Reimplemented from UwModem.
References hdr_uwal::binPktLength(), UwModem::ERROR, initLUT_, UwModem::printOnLog(), and size2dur_.
Referenced by recv(), and recvSyncClMsg().
initializeLUT()
void UwEvoLogicsS2CModem::initializeLUT () virtual
Method that loads the TX LUT into a map. Also adds the processing delay if any.
References UwModem::ERROR, initLUT_, UwModem::printOnLog(), size2dur_, txdur_file_name_, and txdur_token_separator_.
Referenced by command().
receivingData()
void UwEvoLogicsS2CModem::receivingData () private virtual
Mehod that detach a thread devoted to receiving data from the connector.
References UwModem::data_buffer, UwModem::DATA_BUFFER_LEN, UwModem::DEBUG, UwModem::MAX_READ_BYTES, UwInterpreterS2C::NO_COMMAND, p_connector, p_interpreter, UwModem::printOnLog(), receiving, rx_payload, and updateStatus().
Referenced by start().
recv()
void UwEvoLogicsS2CModem::recv (Packet * p) virtual
Method that handles the reception of packets arriving from upper layers of the network simulator.
Parameters
p pointer to the packet that has been received from the simulator upper layers
Implements UwModem.
References UwModem::DEBUG, endRx(), UwModem::getModulationType(), getTxDuration(), UwModem::printOnLog(), startRx(), UwModem::tx_queue, tx_queue_cv, and tx_queue_m.
recvSyncClMsg()
int UwEvoLogicsS2CModem::recvSyncClMsg (ClMessage * m) virtual
Cross-Layer messages synchronous interpreter.
Parameters
ClMessage* an instance of ClMessage that represent the message received
Returns
0 if successful.
Implements UwModem.
References BURST, CLMSG_S2C_POWER_LEVEL, CLMSG_S2C_RX_FAILED, CLMSG_S2C_TX_MODE, curr_source_level, ClMsgS2CPowerLevel::get_power_level(), ClMsgUwPhy::GET_REPLY, ClMsgUwPhy::GET_REQ, ClMsgS2CTxMode::get_tx_mode(), ClMsgUwPhy::getReqType(), getTxDuration(), IM, UwModem::INFO, n_rx_failed, pend_source_level, UwModem::printOnLog(), ClMsgS2CTxMode::S2C_TX_MODE_BURST, ClMsgS2CTxMode::S2C_TX_MODE_IM, ClMsgS2CRxFailed::set_n_rx_failed(), ClMsgS2CPowerLevel::set_power_level(), ClMsgUwPhy::SET_REPLY, ClMsgUwPhy::SET_REQ, ClMsgS2CTxMode::set_tx_mode(), ClMsgUwPhy::setReqType(), source_level_change, and tx_mode.
setFailedTx()
void UwEvoLogicsS2CModem::setFailedTx (Packet * p) private
Method that allows to set the error flag on the packet to notify upper layers about un-tranmsitted packets due to, e.g., modem unavailability.
Parameters
p Packet pointer ot the packet being transmitted
start()
void UwEvoLogicsS2CModem::start () private virtual
Method that starts the driver operations. It performs all the needed operations to correctly fire up the device's driver.
Implements UwModem.
References UwModem::CheckTimer, UwModem::checkTimer, UwModem::ERROR, UwModem::modem_address, p_connector, UwModem::period, UwModem::printOnLog(), receiving, receivingData(), rx_thread, transmitting, transmittingData(), and tx_thread.
Referenced by command().
startRx()
void UwEvoLogicsS2CModem::startRx (Packet * p) private virtual
Method that starts a packet reception. This method is also in charge of sending a ClMsg, Phy2MacStartRx(p), to notify the upper layers of the simulator about the start of the reception
Parameters
p Packet pointer to the packet to be received
Implements UwModem.
References UwModem::INFO, and UwModem::printOnLog().
Referenced by recv().
startTx()
void UwEvoLogicsS2CModem::startTx (Packet * p) private virtual
Method that triggers the transmission of a packet through a specified modem.
Parameters
p Packet pointer to the packet to be sent
Implements UwModem.
References ack_mode, AVAILABLE, hdr_uwal::binPkt(), hdr_uwal::binPktLength(), BUSY, UwModem::DEBUG, UwModem::ERROR, UwModem::event_q, IM, im_status_updated, UwModem::INFO, MAX_N_STATUS_QUERIES, MODEM_TIMEOUT, p_connector, p_interpreter, UwModem::printOnLog(), UwModem::realTxEnded(), status, status_cv, status_m, TX_IDLE, tx_mode, TX_PENDING, tx_status, tx_status_cv, tx_status_m, WAIT_DELIVERY_BURST, and WAIT_DELIVERY_IM.
Referenced by transmittingData().
stop()
void UwEvoLogicsS2CModem::stop () private virtual
Method that stops the driver operations. It performs all the needed operations to correctly stop the device's driver before closing the simulation.
Implements UwModem.
References UwModem::checkTimer, UwModem::ERROR, UwModem::INFO, p_connector, UwModem::printOnLog(), receiving, rx_thread, transmitting, tx_queue_cv, and tx_thread.
Referenced by command(), and ~UwEvoLogicsS2CModem().
transmittingData()
void UwEvoLogicsS2CModem::transmittingData () private virtual
Method that detach a thread devoted to sending packets found in tx_queue.
References UwModem::DEBUG, UwModem::printOnLog(), startTx(), transmitting, UwModem::tx_queue, tx_queue_cv, and tx_queue_m.
Referenced by start().
updateStatus()
void UwEvoLogicsS2CModem::updateStatus (UwInterpreterS2C::Response cmd) private
Method that updates the status of the modem State Machine: state change is triggered by reception of commands on the connector interface, or by commands to be sent to the device, e.g., SEND or SENDIM.
Parameters
cmd command received on the connector interface
References AVAILABLE, UwInterpreterS2C::BITRATE, UwInterpreterS2C::BUFF_NOT_EMPTY, UwInterpreterS2C::BUFFER_FULL, BUSY, UwInterpreterS2C::BUSY, UwInterpreterS2C::CONN_CLOSED, createRxPacket(), DEAF, UwModem::DEBUG, UwInterpreterS2C::DELIVERED, UwInterpreterS2C::DELIVERING, UwInterpreterS2C::DROPCNT, UwInterpreterS2C::EMPTY, UwModem::event_q, UwInterpreterS2C::FAIL, im_status_updated, UwModem::INFO, UwInterpreterS2C::INIT_DEAF, UwInterpreterS2C::INIT_LISTEN, UwInterpreterS2C::INIT_NOISE, UwInterpreterS2C::INTERNAL, n_rx_failed, NOISE, UwInterpreterS2C::NOT_ACCEPTED, UwInterpreterS2C::OK, UwInterpreterS2C::OUT_OF_RANGE, p_interpreter, UwInterpreterS2C::PHYOFF, UwModem::printOnLog(), UwInterpreterS2C::PROTOCOL_ID, QUIT, UwInterpreterS2C::RECV, UwModem::recv(), UwInterpreterS2C::RECVEND, UwInterpreterS2C::RECVFAIL, UwInterpreterS2C::RECVIM, UwInterpreterS2C::RECVSTART, RESET, UwInterpreterS2C::SENDEND, UwInterpreterS2C::SENDSTART, status, status_cv, status_m, TX_IDLE, tx_status, tx_status_cv, tx_status_m, UwInterpreterS2C::UNKNOWN, UwInterpreterS2C::USBLANGLES, UwInterpreterS2C::USBLLONG, and UwInterpreterS2C::WRONG_ADDR.
Referenced by receivingData().
Member Data Documentation
ack_mode
bool UwEvoLogicsS2CModem::ack_mode private
Set to true to enable IM ack
Referenced by command(), and startTx().
curr_source_level
int UwEvoLogicsS2CModem::curr_source_level private
Current source level already set in device
Referenced by recvSyncClMsg().
EPSILON_S
const double UwEvoLogicsS2CModem::EPSILON_S static private
Minimum time to wait before to schedule a new event in seconds
im_status_updated
std::atomic<bool> UwEvoLogicsS2CModem::im_status_updated private
Atomic boolean variable controlling if the modem had responded to ATDI
Referenced by startTx(), and updateStatus().
initLUT_
bool UwEvoLogicsS2CModem::initLUT_ private
Flag that tells whether the TX duration LUT is loaded or not.
Referenced by getTxDuration(), and initializeLUT().
MAX_N_STATUS_QUERIES
uint UwEvoLogicsS2CModem::MAX_N_STATUS_QUERIES = 10 static private
Maximum number of time to query the modem transmission status before to discard the transmitted packet
Referenced by startTx(), and UwEvoLogicsS2CModem().
MODEM_TIMEOUT
const std::chrono::milliseconds UwEvoLogicsS2CModem::MODEM_TIMEOUT static private
Initial value:
=
        std::chrono::milliseconds(210)
Maximum time to wait for modem to become ModemState::AVAILABLE
Referenced by configure(), and startTx().
n_rx_failed
int UwEvoLogicsS2CModem::n_rx_failed private
Number of failed receptions up to now
Referenced by recvSyncClMsg(), and updateStatus().
p_connector
std::unique_ptr<UwConnector> UwEvoLogicsS2CModem::p_connector private
Pointer to Connector object that interfaces with the device
Referenced by command(), configure(), receivingData(), start(), startTx(), and stop().
p_interpreter
std::unique_ptr<UwInterpreterS2C> UwEvoLogicsS2CModem::p_interpreter private
Pointer to Interpreter object to parse device syntax
Referenced by command(), configure(), receivingData(), startTx(), and updateStatus().
pend_source_level
int UwEvoLogicsS2CModem::pend_source_level private
Pending source level, requested but not set
Referenced by configure(), and recvSyncClMsg().
receiving
std::atomic<bool> UwEvoLogicsS2CModem::receiving private
Atomic boolean variable that controls the receiving looping thread
Referenced by receivingData(), start(), and stop().
rx_payload
std::string UwEvoLogicsS2CModem::rx_payload private
String that is updated witn each new received messsage
Referenced by createRxPacket(), and receivingData().
rx_thread
std::thread UwEvoLogicsS2CModem::rx_thread private
Object with the rx thread
Referenced by start(), and stop().
size2dur_
TransmissionDurationLUT UwEvoLogicsS2CModem::size2dur_ private
Map from size [byte] to TX duration [s].
Referenced by getTxDuration(), and initializeLUT().
source_level_change
bool UwEvoLogicsS2CModem::source_level_change private
Flag that tells a new SL value to be applied
Referenced by recvSyncClMsg().
status
ModemState UwEvoLogicsS2CModem::status private
Variable holding the current status of the modem
Referenced by configure(), startTx(), and updateStatus().
status_cv
std::condition_variable UwEvoLogicsS2CModem::status_cv private
Condition variable to wait for ModemState::AVAILABLE
Referenced by configure(), startTx(), and updateStatus().
status_m
std::mutex UwEvoLogicsS2CModem::status_m private
Mutex associated with the state machine of the modem
Referenced by configure(), startTx(), and updateStatus().
transmitting
std::atomic<bool> UwEvoLogicsS2CModem::transmitting private
Atomic boolean variable that controls the transmitting looping thread
Referenced by start(), stop(), and transmittingData().
tx_mode
TransmissionMode UwEvoLogicsS2CModem::tx_mode private
Either burst or im.
Referenced by command(), recvSyncClMsg(), and startTx().
tx_queue_cv
std::condition_variable UwEvoLogicsS2CModem::tx_queue_cv private
Condition variable that is linked with the transmitting queue
Referenced by recv(), stop(), and transmittingData().
tx_queue_m
std::mutex UwEvoLogicsS2CModem::tx_queue_m private
Mutex associated with the transmission queue
Referenced by recv(), and transmittingData().
tx_status
TransmissionState UwEvoLogicsS2CModem::tx_status private
Variable holding the current transmission status of the modem
Referenced by configure(), startTx(), and updateStatus().
tx_status_cv
std::condition_variable UwEvoLogicsS2CModem::tx_status_cv private
Condition variable to wait for TransmissionState::TX_IDLE
Referenced by startTx(), and updateStatus().
tx_status_m
std::mutex UwEvoLogicsS2CModem::tx_status_m private
Mutex associated with the transmission state machine of the modem
Referenced by configure(), startTx(), and updateStatus().
tx_thread
std::thread UwEvoLogicsS2CModem::tx_thread private
Object with the tx thread
Referenced by start(), and stop().
txdur_file_name_
std::string UwEvoLogicsS2CModem::txdur_file_name_ private
TX duration LUT file name.
Referenced by command(), and initializeLUT().
txdur_token_separator_
char UwEvoLogicsS2CModem::txdur_token_separator_ private
TX duration LUT separator.
Referenced by command(), and initializeLUT().
virtual_time_ref
double UwEvoLogicsS2CModem::virtual_time_ref private
virtual time reference
WAIT_DELIVERY_BURST
const std::chrono::seconds UwEvoLogicsS2CModem::WAIT_DELIVERY_BURST static private
Initial value:
=
        std::chrono::seconds(5)
Time interval tu wait for a burst message tobe confirmed through a DELIVERED response. Given in SECONDS
Referenced by startTx().
WAIT_DELIVERY_IM
const std::chrono::milliseconds UwEvoLogicsS2CModem::WAIT_DELIVERY_IM static private
Initial value:
=
        std::chrono::milliseconds(200)
Time interval to wait for the modem notifying that there no more IM in its queue and a new IM can be sent
Referenced by startTx().
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/physical/uwevologicss2cmodem/uwevologicss2cmodem.h
DESERT_Framework/DESERT/physical/uwevologicss2cmodem/uwevologicss2cmodem.cpp