DESERT: uwUFetch_NODE::uwUFetch_NODE_timer Class Reference
uwUFetch_NODE::uwUFetch_NODE_timer Class Reference
#include <uwUFetch_NODE.h>
Public Member Functions
uwUFetch_NODE_timer (uwUFetch_NODE *m)
virtual ~uwUFetch_NODE_timer ()
virtual void freeze ()
virtual void unFreeze ()
virtual void stop ()
virtual void schedule (double val)
bool isIdle ()
bool isRunning ()
bool isFroozen ()
bool isExpired ()
bool isActive ()
void resetCounter ()
void incrCounter ()
int getCounter ()
double getDuration ()
Protected Attributes
double start_time
double left_duration
int counter
uwUFetch_NODE *UWUFETCH_TIMER_STATUS timer_status
Detailed Description
Class that handle the timers of SN or HN
Constructor & Destructor Documentation
uwUFetch_NODE_timer()
uwUFetch_NODE::uwUFetch_NODE_timer::uwUFetch_NODE_timer (uwUFetch_NODE * m) inline
Constructor of the class uwUFetch_NODE_timer
Parameters
m pointer to uwUFetch_NODE class
~uwUFetch_NODE_timer()
virtual uwUFetch_NODE::uwUFetch_NODE_timer::~uwUFetch_NODE_timer () inline virtual
Destructor of the class uwUFetch_NODE_timer
Member Function Documentation
freeze()
virtual void uwUFetch_NODE::uwUFetch_NODE_timer::freeze () inline virtual
Freeze the timer
References left_duration, start_time, timer_status, uwUFetch_NODE::UWUFETCH_TIMER_STATUS_FROZEN, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_RUNNING.
getCounter()
int uwUFetch_NODE::uwUFetch_NODE_timer::getCounter () inline
value of the counter
Returns
int counter
References counter.
getDuration()
double uwUFetch_NODE::uwUFetch_NODE_timer::getDuration () inline
left duration of the timer
Returns
double left_duration
References left_duration.
incrCounter()
void uwUFetch_NODE::uwUFetch_NODE_timer::incrCounter () inline
increment the counter by one value
References counter.
isActive()
bool uwUFetch_NODE::uwUFetch_NODE_timer::isActive () inline
verify if the timer is ACTIVE
Returns
: bool true ACTIVE
References isFroozen(), isRunning(), and timer_status.
isExpired()
bool uwUFetch_NODE::uwUFetch_NODE_timer::isExpired () inline
verify whether the timer is EXPIRED
Returns
: bool true EXPIRED
References timer_status, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_EXPIRED.
isFroozen()
bool uwUFetch_NODE::uwUFetch_NODE_timer::isFroozen () inline
verify if the timer is FROZEN
Returns
: bool true FROZEN
References timer_status, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_FROZEN.
Referenced by isActive().
isIdle()
bool uwUFetch_NODE::uwUFetch_NODE_timer::isIdle () inline
verify whether the timer is IDLE
Returns
: bool true-->IDLE
References timer_status, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_IDLE.
isRunning()
bool uwUFetch_NODE::uwUFetch_NODE_timer::isRunning () inline
verify if the timer is RUNNING
Returns
: bool true RUNNING
References timer_status, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_RUNNING.
Referenced by isActive().
resetCounter()
void uwUFetch_NODE::uwUFetch_NODE_timer::resetCounter () inline
reset the counter that scan the timer
schedule()
virtual void uwUFetch_NODE::uwUFetch_NODE_timer::schedule (double val) inline virtual
schedule a timer
Parameters
double the duration of the timer
References left_duration, start_time, timer_status, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_RUNNING.
Referenced by uwUFetch_NODE::BEACON_rx(), uwUFetch_NODE::CBEACON_rx(), uwUFetch_NODE::Phy2MacEndRx(), uwUFetch_NODE::Phy2MacEndTx(), uwUFetch_NODE::Phy2MacEndTx_HN(), uwUFetch_NODE::state_wait_CBEACON(), uwUFetch_NODE::state_wait_CTS(), uwUFetch_NODE::state_wait_first_DATA(), uwUFetch_NODE::state_wait_POLL(), uwUFetch_NODE::state_wait_PROBE(), uwUFetch_NODE::stateIdle_HN(), uwUFetch_NODE::TRIGGER_rx(), and uwUFetch_NODE::TRIGGER_rx_without().
stop()
virtual void uwUFetch_NODE::uwUFetch_NODE_timer::stop () inline virtual
Stop the timer
References timer_status, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_IDLE.
unFreeze()
virtual void uwUFetch_NODE::uwUFetch_NODE_timer::unFreeze () inline virtual
unFreeze are used after a freezing of the timer. In this case the timer restart from the timer where was freezed
check the state of the timer before sheduling the event. If the timer is set, then the call are aborted
References left_duration, start_time, timer_status, uwUFetch_NODE::UWUFETCH_TIMER_STATUS_FROZEN, and uwUFetch_NODE::UWUFETCH_TIMER_STATUS_RUNNING.
Member Data Documentation
counter
int uwUFetch_NODE::uwUFetch_NODE_timer::counter protected
Counter of the timer
Referenced by getCounter(), and incrCounter().
left_duration
double uwUFetch_NODE::uwUFetch_NODE_timer::left_duration protected
Left duration of the timer
Referenced by freeze(), getDuration(), schedule(), and unFreeze().
start_time
double uwUFetch_NODE::uwUFetch_NODE_timer::start_time protected
Time to start the timer
Referenced by freeze(), schedule(), and unFreeze().
timer_status
uwUFetch_NODE* UWUFETCH_TIMER_STATUS uwUFetch_NODE::uwUFetch_NODE_timer::timer_status protected
< Pointer to an object of type uwUFetch_NODE Timer status
Referenced by uwUFetch_NODE::uwUFetch_BEACON_timer::expire(), uwUFetch_NODE::uwUFetch_BackOffTimer::expire(), freeze(), isActive(), isExpired(), isFroozen(), isIdle(), isRunning(), schedule(), stop(), and unFreeze().
The documentation for this class was generated from the following file:
DESERT_Framework/DESERT/data_link/uwUFetch/uwUFetch_NODE.h