DESERT: UwTrackerModule Class Reference
UwTrackerModule Class Reference
#include <uwtracker-module.h>
Public Member Functions
UwTrackerModule ()
UwTrackerModule (UWSMPosition *p)
virtual ~UwTrackerModule ()
virtual int command (int argc, const char *const *argv)
virtual void initPkt (Packet *p)
Public Member Functions inherited from UwCbrModule
UwCbrModule ()
virtual ~UwCbrModule ()=default
virtual void recv (Packet *) override
virtual void recv (Packet *p, Handler *h) override
virtual double GetRTT () const
virtual double GetFTT () const
virtual double GetTxTime () const
virtual double GetPER () const
virtual double GetTHR () const
virtual double GetRTTstd () const
virtual double GetFTTstd () const
virtual void resetStats ()
void printIdsPkts () const
Protected Member Functions
virtual void printReceivedPacket (Packet *p)
void sendPkt ()
void updateTrackMeasure ()
virtual void start ()
virtual void stop ()
Protected Member Functions inherited from UwCbrModule
virtual void sendPktLowPriority ()
virtual void sendPktHighPriority ()
virtual void transmit ()
virtual void updateRTT (const double &)
virtual void updateFTT (const double &)
virtual void updateThroughput (const int &, const double &)
virtual void incrPktLost (const int &)
virtual void incrPktRecv ()
virtual void incrPktOoseq ()
virtual void incrPktInvalid ()
virtual double getTimeBeforeNextPkt ()
Protected Attributes
UWSMPosition * track_position
hdr_uwTracker track_measure
double max_tracking_distance
int send_only_active_trace
int track_my_position
double tracking_period
UwUpdateTrackMeasure measure_timer
Protected Attributes inherited from UwCbrModule
uint16_t dstPort_
std::string log_suffix
nsaddr_t dstAddr_
char priority_
std::ofstream tracefile
std::string tracefilename
bool * sn_check
int PoissonTraffic_
int debug_
int drop_out_of_order_
uint traffic_type_
UwSendTimer sendTmr_
int txsn
int hrsn
int pkts_recv
int pkts_ooseq
int pkts_lost
int pkts_invalid
int pkts_last_reset
int cnt
double rftt
double srtt
double sftt
double lrtime
double sthr
double period_
int pktSize_
double sumrtt
double sumrtt2
int rttsamples
double sumftt
double sumftt2
int fttsamples
double sumtxtimes = 0
double sumbytes
double sumdt
uint32_t esn
int tracefile_enabler_
Friends
class UwUpdateTrackMeasure
Additional Inherited Members
Static Protected Member Functions inherited from UwCbrModule
static int getCbrHeaderSize ()
Static Protected Attributes inherited from UwCbrModule
static int uidcnt_ = 0
Detailed Description
UwTrackerModule class is used to track mobile nodes via sonar and share tracking information via packets.
Constructor & Destructor Documentation
UwTrackerModule() [1/2]
UwTrackerModule::UwTrackerModule ()
Default Constructor of UwTrackerModule class.
References max_tracking_distance, send_only_active_trace, and tracking_period.
UwTrackerModule() [2/2]
UwTrackerModule::UwTrackerModule (UWSMPosition * p)
Constructor with position setting of UwTrackerModule class.
Parameters
UWSMPosition* p Pointer to the track position
References max_tracking_distance, send_only_active_trace, track_my_position, and tracking_period.
~UwTrackerModule()
UwTrackerModule::~UwTrackerModule () virtual
Destructor of UwTrackerModule class.
Member Function Documentation
command()
int UwTrackerModule::command (int argc, const char *const * argv) virtual
TCL command interpreter. It implements the following OTcl methods:
Parameters
argc Number of arguments in argv.
argv Array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not.
Reimplemented from UwCbrModule.
Reimplemented in UwSCFTrackerModule, and UwSCTrackerModule.
References UwCbrModule::command(), max_tracking_distance, track_my_position, and track_position.
Referenced by UwSCFTrackerModule::command(), and UwSCTrackerModule::command().
initPkt()
void UwTrackerModule::initPkt (Packet * p) virtual
Initializes a monitoring data packet passed as argument with the default values.
Parameters
Packet* Pointer to a packet already allocated to fill with the right values.
Reimplemented from UwCbrModule.
Reimplemented in UwSCFTrackerModule.
References UwCbrModule::debug_, UwCbrModule::initPkt(), printReceivedPacket(), hdr_uwTracker::speed(), track_measure, track_my_position, hdr_uwTracker::x(), hdr_uwTracker::y(), and hdr_uwTracker::z().
Referenced by UwSCFTrackerModule::initPkt().
printReceivedPacket()
void UwTrackerModule::printReceivedPacket (Packet * p) protected virtual
Print to tracefile details about a received packet
Parameters
Packet* Pointer to the received packet
Reimplemented from UwCbrModule.
References hdr_uwip::access(), hdr_uwip::daddr(), max_tracking_distance, hdr_uwip::saddr(), hdr_uwcbr::sn(), hdr_uwTracker::speed(), hdr_uwTracker::timestamp(), UwCbrModule::tracefile, UwCbrModule::tracefile_enabler_, track_my_position, hdr_uwTracker::x(), hdr_uwTracker::y(), and hdr_uwTracker::z().
Referenced by initPkt().
sendPkt()
void UwTrackerModule::sendPkt () protected virtual
Allocates, initialize and sends a packet with the default priority flag set from tcl.
Reimplemented from UwCbrModule.
References max_tracking_distance, send_only_active_trace, UwCbrModule::sendPkt(), track_measure, hdr_uwTracker::x(), hdr_uwTracker::y(), and hdr_uwTracker::z().
Referenced by UwSCFTrackerModule::sendPkt().
start()
void UwTrackerModule::start () protected virtual
Start to send packets.
Reimplemented from UwCbrModule.
Reimplemented in UwSCFTrackerModule.
References measure_timer, UwCbrModule::start(), and tracking_period.
Referenced by UwSCFTrackerModule::start().
stop()
void UwTrackerModule::stop () protected virtual
Stop to send packets.
Reimplemented from UwCbrModule.
Reimplemented in UwSCFTrackerModule.
References measure_timer, and UwCbrModule::stop().
Referenced by UwSCFTrackerModule::stop().
updateTrackMeasure()
void UwTrackerModule::updateTrackMeasure () protected
Update the track measure
References UWSMPosition::getSpeed(), UWSMPosition::getX(), UWSMPosition::getY(), UWSMPosition::getZ(), measure_timer, hdr_uwTracker::speed(), hdr_uwTracker::timestamp(), track_measure, track_position, tracking_period, hdr_uwTracker::x(), hdr_uwTracker::y(), and hdr_uwTracker::z().
Friends And Related Symbol Documentation
UwUpdateTrackMeasure
friend class UwUpdateTrackMeasure friend
Member Data Documentation
max_tracking_distance
double UwTrackerModule::max_tracking_distance protected
Maximum tracking distance, in [m]
Referenced by command(), printReceivedPacket(), sendPkt(), UwTrackerModule(), and UwTrackerModule().
measure_timer
UwUpdateTrackMeasure UwTrackerModule::measure_timer protected
timer to schedule tracking measurements
Referenced by start(), stop(), UwSCFTrackerModule::updateMineRemove(), and updateTrackMeasure().
send_only_active_trace
int UwTrackerModule::send_only_active_trace protected
send only active trace
Referenced by sendPkt(), UwTrackerModule(), and UwTrackerModule().
track_measure
hdr_uwTracker UwTrackerModule::track_measure protected
Track position.
Referenced by initPkt(), UwSCFTrackerModule::initPkt(), UwSCFTrackerModule::sendPkt(), sendPkt(), UwSCFTrackerModule::updateMineRemove(), and updateTrackMeasure().
track_my_position
int UwTrackerModule::track_my_position protected
track also my position
Referenced by command(), initPkt(), printReceivedPacket(), and UwTrackerModule().
track_position
UWSMPosition* UwTrackerModule::track_position protected
Track position.
Referenced by command(), UwSCFTrackerModule::command(), UwSCFTrackerModule::sendPkt(), UwSCFTrackerModule::updateMineRemove(), updateTrackMeasure(), and UwSCFTrackerModule::updateTrackPosition().
tracking_period
double UwTrackerModule::tracking_period protected
period between tracking measurements
Referenced by UwSCFTrackerModule::sendPkt(), start(), UwSCFTrackerModule::start(), UwSCFTrackerModule::updateMineRemove(), updateTrackMeasure(), UwTrackerModule(), and UwTrackerModule().
The documentation for this class was generated from the following files:
DESERT_Addons/uwtracker/uwtracker-module.h
DESERT_Addons/uwtracker/uwtracker-module.cpp