DESERT: UwMultiPhyControl Class Reference
UwMultiPhyControl Class Reference
#include <uwmulti-multiphy-controller.h>
Classes
class ProbeTimer
class ResilienceTimer
Public Member Functions
UwMultiPhyControl ()
virtual ~UwMultiPhyControl ()
virtual int command (int, const char *const *)
void recv (Packet *p)
void recv (Packet *p, int idSrc)
Private Member Functions
void initialize ()
int getBestMacID (int trafficType, int remoteIP)
void updateAvailability (RemoteConnection c, LinkStatus status)
void sendPing (RemoteConnection c)
void recvFromUpperLayers (Packet *p)
void recvFromLowerLayers (Packet *p, int macID)
Private Attributes
int debug_
int localIP
std::vector< int > macIDs
std::queue< Packet * > packet_queue
std::map< int, double > resilienceTimeouts
std::map< RemoteConnection, ResilienceTimer > resilienceTimers
std::map< int, double > probeTimeouts
std::map< RemoteConnection, ProbeTimer > probeTimers
PriorityMap priorityMap
std::map< RemoteConnection, int > linkStatuses
std::map< int, int > macResilience
std::map< int, int > macTclIdLayerId
Detailed Description
Class used to represents the UwMultiPhyControl layer of a node.
Constructor & Destructor Documentation
UwMultiPhyControl()
UwMultiPhyControl::UwMultiPhyControl ()
Constructor of UwMultiPhy class.
References debug_, and priorityMap.
~UwMultiPhyControl()
virtual UwMultiPhyControl::~UwMultiPhyControl () inline virtual
Destructor of UwMultiPhy class.
Member Function Documentation
command()
int UwMultiPhyControl::command (int argc, const char *const * argv) virtual
References PriorityMap::addCustomPriority(), getBestMacID(), initialize(), LocalConnection::localMacID, macResilience, macTclIdLayerId, priorityMap, probeTimeouts, resilienceTimeouts, PriorityMap::setDefaultPriority(), and LocalConnection::trafficType.
getBestMacID()
int UwMultiPhyControl::getBestMacID (int trafficType, int remoteIP) private
References PriorityMap::getPriority(), LINK_OK, linkStatuses, LocalConnection::localMacID, RemoteConnection::localMacID, macIDs, priorityMap, RemoteConnection::remoteIP, and LocalConnection::trafficType.
Referenced by command(), and recvFromUpperLayers().
initialize()
void UwMultiPhyControl::initialize () private
References debug_, UWIPClMsgSendAddr::getAddr(), localIP, macIDs, and macTclIdLayerId.
Referenced by command().
recv() [1/2]
void UwMultiPhyControl::recv (Packet * p)
recv() [2/2]
void UwMultiPhyControl::recv (Packet * p, int idSrc)
References recvFromLowerLayers(), and recvFromUpperLayers().
recvFromLowerLayers()
void UwMultiPhyControl::recvFromLowerLayers (Packet * p, int macID) private
References hdr_uwip::daddr(), debug_, LINK_OK, localIP, RemoteConnection::localMacID, packet_queue, printType(), PT_UWCBR, PT_UWMULTIPHY_DATA, PT_UWMULTIPHY_PING, PT_UWMULTIPHY_PONG, recvFromUpperLayers(), RemoteConnection::remoteIP, hdr_uwip::saddr(), and updateAvailability().
Referenced by recv().
recvFromUpperLayers()
void UwMultiPhyControl::recvFromUpperLayers (Packet * p) private
References hdr_uwip::daddr(), debug_, getBestMacID(), LINK_UNKNOWN, linkStatuses, localIP, RemoteConnection::localMacID, macIDs, packet_queue, printType(), PT_UWMULTIPHY_DATA, RemoteConnection::remoteIP, sendPing(), and hdr_uwcbr::traffic_type().
Referenced by recv(), and recvFromLowerLayers().
sendPing()
void UwMultiPhyControl::sendPing (RemoteConnection c) private
References hdr_uwip::daddr(), debug_, LINK_PROBING, LINK_UNKNOWN, linkStatuses, localIP, RemoteConnection::localMacID, printType(), probeTimeouts, probeTimers, PT_UWMULTIPHY_PING, RemoteConnection::remoteIP, and hdr_uwip::saddr().
Referenced by recvFromUpperLayers().
updateAvailability()
void UwMultiPhyControl::updateAvailability (RemoteConnection c, LinkStatus status) private
References debug_, LINK_OK, LINK_PROBING, linkStatuses, localIP, RemoteConnection::localMacID, probeTimers, RemoteConnection::remoteIP, resilienceTimeouts, and resilienceTimers.
Referenced by recvFromLowerLayers().
Member Data Documentation
debug_
int UwMultiPhyControl::debug_ private
Referenced by initialize(), recvFromLowerLayers(), recvFromUpperLayers(), sendPing(), updateAvailability(), and UwMultiPhyControl().
linkStatuses
std::map<RemoteConnection, int> UwMultiPhyControl::linkStatuses private
Referenced by getBestMacID(), recvFromUpperLayers(), sendPing(), and updateAvailability().
localIP
int UwMultiPhyControl::localIP private
Referenced by initialize(), recvFromLowerLayers(), recvFromUpperLayers(), sendPing(), and updateAvailability().
macIDs
std::vector<int> UwMultiPhyControl::macIDs private
Referenced by getBestMacID(), initialize(), and recvFromUpperLayers().
macResilience
std::map<int, int> UwMultiPhyControl::macResilience private
<macID, resilience> where resilience score enstablish an order across local MAC layers: if a less robust one is LINK_OK all higher ones will be as well
Referenced by command().
macTclIdLayerId
std::map<int, int> UwMultiPhyControl::macTclIdLayerId private
Referenced by command(), and initialize().
packet_queue
std::queue<Packet *> UwMultiPhyControl::packet_queue private
Referenced by recvFromLowerLayers(), and recvFromUpperLayers().
priorityMap
PriorityMap UwMultiPhyControl::priorityMap private
Referenced by command(), getBestMacID(), and UwMultiPhyControl().
probeTimeouts
std::map<int, double> UwMultiPhyControl::probeTimeouts private
Referenced by command(), and sendPing().
probeTimers
std::map<RemoteConnection, ProbeTimer> UwMultiPhyControl::probeTimers private
Referenced by sendPing(), and updateAvailability().
resilienceTimeouts
std::map<int, double> UwMultiPhyControl::resilienceTimeouts private
Referenced by command(), and updateAvailability().
resilienceTimers
std::map<RemoteConnection, ResilienceTimer> UwMultiPhyControl::resilienceTimers private
Referenced by updateAvailability().
The documentation for this class was generated from the following files:
DESERT_Addons/uwmulti_traffic_control/uwmulti-multiphy-controller.h
DESERT_Addons/uwmulti_traffic_control/uwmulti-multiphy-controller.cpp