DESERT: UwModemCSA Class Reference
UwModemCSA Class Reference
#include <uwmodemcsa.h>
Public Member Functions
UwModemCSA ()
virtual ~UwModemCSA ()
virtual void recv (Packet *p)
virtual int recvSyncClMsg (ClMessage *m)
virtual double getTxDuration (Packet *p)
virtual int command (int argc, const char *const *argv)
Public Member Functions inherited from UwModem
UwModem ()
virtual ~UwModem ()
virtual int getModulationType (Packet *P)
void setModemID (int ID)
int getModemID ()
void printOnLog (LogLevel log_level, string module, string message)
LogLevel getLogLevel ()
int getDebug ()
std::string getLogFile ()
void realTxEnded (Packet *p)
Private Member Functions
virtual void startTx (Packet *p)
virtual void startRx (Packet *p)
virtual void endRx (Packet *p)
virtual void start ()
virtual void stop ()
virtual void transmittingData ()
virtual void receivingData ()
virtual std::string findCommand (std::vector< char >::iterator beg_it, std::vector< char >::iterator end_it, std::vector< char >::iterator &cmd_b, std::vector< char >::iterator &cmd_e)
virtual bool parseCommand (std::vector< char >::iterator cmd_b, std::vector< char >::iterator cmd_e, std::string &rx_payload)
virtual std::string buildSend (const std::string &payload, int dest)
void startRealRx (const std::string &cmd)
void createRxPacket (Packet *p)
Private Attributes
std::unique_ptr< UwConnector > p_connector
ModemState status
std::mutex status_m
std::mutex tx_queue_m
std::condition_variable status_cv
std::condition_variable tx_queue_cv
std::atomic< bool > receiving
std::atomic< bool > transmitting
std::thread rx_thread
std::thread tx_thread
std::string rx_payload
std::string del_b
std::string del_e
Static Private Attributes
static const std::chrono::milliseconds MODEM_TIMEOUT
static const double EPSILON_S = 0.01
static const size_t MAX_TX_STATUS_POLL = 20
Additional Inherited Members
Public Types inherited from UwModem
enum class LogLevel { ERROR = 0 , INFO = 1 , DEBUG = 2 }
Static Public Member Functions inherited from UwModem
static bool string2log (const std::string &ll_string, LogLevel &ll)
static bool log2string (LogLevel ll, std::string &ll_string)
Protected Member Functions inherited from UwModem
virtual void endTx (Packet *p)
void checkEvent ()
Protected Attributes inherited from UwModem
int modemID
std::vector< char > data_buffer
std::queue< Packet * > tx_queue
std::queue< Packet * > rx_queue
unsigned int DATA_BUFFER_LEN
int MAX_READ_BYTES
std::string modem_address
int debug_
std::ofstream outLog
std::string logFile
std::string log_suffix
LogLevel loglevel_
bool log_is_open
CheckTimer * checkTimer
double period
std::queue< ModemEvent > event_q
Constructor & Destructor Documentation
UwModemCSA()
UwModemCSA::UwModemCSA ()
Constructor of the UwModemCSA class
Parameters
address string containing the address to connect to
buflen lenght in char of the data buffer
read len length in char of a signle read from the connector
References UwModem::DATA_BUFFER_LEN, and UwModem::MAX_READ_BYTES.
~UwModemCSA()
UwModemCSA::~UwModemCSA () virtual
Destructor of the UwModemCSA class
References stop().
Member Function Documentation
buildSend()
std::string UwModemCSA::buildSend (const std::string & payload, int dest) private virtual
Referenced by startTx().
command()
int UwModemCSA::command (int argc, const char *const * argv) virtual
Tcl command interpreter: Method that maps Tcl commands into C++ methods.
Parameters
argc number of arguments in argv
argv array of strings which are the command parameters (Note that argv[0] is the name of the object).
Returns
TCL_OK or TCL_ERROR whether the command has been dispatched successfully or not
Reimplemented from UwModem.
References UwModem::command(), and p_connector.
createRxPacket()
void UwModemCSA::createRxPacket (Packet * p) private
References hdr_uwal::binPkt(), hdr_uwal::binPktLength(), and rx_payload.
Referenced by startRealRx().
endRx()
void UwModemCSA::endRx (Packet * p) private virtual
Method that ends a packet reception. This method is also in charge of sending the received NS-MIRACLE packet to the upper layers
Parameters
p Packet pointer to the packet being sent
Implements UwModem.
References UwModem::INFO, and UwModem::printOnLog().
Referenced by recv().
findCommand()
std::string UwModemCSA::findCommand (std::vector< char >::iterator beg_it, std::vector< char >::iterator end_it, std::vector< char >::iterator & cmd_b, std::vector< char >::iterator & cmd_e) private virtual
Method that finds the position of a command in a buffer.
References del_b, and del_e.
Referenced by receivingData().
getTxDuration()
double UwModemCSA::getTxDuration (Packet * p) virtual
Method that returns the duration of a given transmitted packet. Inherited from MPhy, in NS-MIRACLE, could be empty if there is no way to retrieve this information.
Parameters
p Packet pointer to the given packet being transmitted
Returns
duration in seconds
Reimplemented from UwModem.
Referenced by recv(), and recvSyncClMsg().
parseCommand()
bool UwModemCSA::parseCommand (std::vector< char >::iterator cmd_b, std::vector< char >::iterator cmd_e, std::string & rx_payload) private virtual
Method that parses the command to obtain the recquired informations.
References rx_payload.
Referenced by receivingData().
receivingData()
void UwModemCSA::receivingData () private virtual
Method that detach a thread devoted to receiving data from the connector.
References UwModem::data_buffer, UwModem::DATA_BUFFER_LEN, findCommand(), UwModem::MAX_READ_BYTES, p_connector, parseCommand(), receiving, rx_payload, and startRealRx().
Referenced by start().
recv()
void UwModemCSA::recv (Packet * p) virtual
Method that handles the reception of packets arriving from upper layers of the network simulator.
Parameters
p pointer to the packet that has been received from the simulator upper layers
Implements UwModem.
References UwModem::DEBUG, endRx(), UwModem::getModulationType(), getTxDuration(), UwModem::printOnLog(), startRx(), UwModem::tx_queue, tx_queue_cv, and tx_queue_m.
recvSyncClMsg()
int UwModemCSA::recvSyncClMsg (ClMessage * m) virtual
Cross-Layer messages synchronous interpreter.
Parameters
ClMessage* an instance of ClMessage that represent the message received
Returns
0 if successful.
Implements UwModem.
References getTxDuration(), UwModem::INFO, and UwModem::printOnLog().
start()
void UwModemCSA::start () private virtual
Method that starts the driver operations. It performs all the needed operations to correctly fire up the device's driver.
Implements UwModem.
References UwModem::CheckTimer, UwModem::checkTimer, UwModem::ERROR, UwModem::modem_address, p_connector, UwModem::period, UwModem::printOnLog(), receiving, receivingData(), rx_thread, transmitting, transmittingData(), and tx_thread.
startRealRx()
void UwModemCSA::startRealRx (const std::string & cmd) private
Method that updates the status of the modem State Machine: state change is triggered by reception of commands on the connector interface, or by commands to be sent to the device, e.g., SEND or SENDIM.
Parameters
cmd command received on the connector interface
References AVAILABLE, createRxPacket(), UwModem::event_q, UwModem::recv(), status, status_cv, and status_m.
Referenced by receivingData().
startRx()
void UwModemCSA::startRx (Packet * p) private virtual
Method that starts a packet reception. This method is also in charge of sending a ClMsg, Phy2MacStartRx(p), to notify the upper layers of the simulator about the start of the reception
Parameters
p Packet pointer to the packet to be received
Implements UwModem.
References UwModem::INFO, and UwModem::printOnLog().
Referenced by recv().
startTx()
void UwModemCSA::startTx (Packet * p) private virtual
Method that triggers the transmission of a packet through a specified modem.
Parameters
p Packet pointer to the packet to be sent
Implements UwModem.
References AVAILABLE, hdr_uwal::binPkt(), hdr_uwal::binPktLength(), buildSend(), BUSY, UwModem::ERROR, UwModem::event_q, UwModem::INFO, MODEM_TIMEOUT, p_connector, UwModem::printOnLog(), UwModem::realTxEnded(), status, status_cv, and status_m.
Referenced by transmittingData().
stop()
void UwModemCSA::stop () private virtual
Method that stops the driver operations. It performs all the needed operations to correctly stop the device's driver before closing the simulation.
Implements UwModem.
References UwModem::checkTimer, UwModem::ERROR, UwModem::INFO, p_connector, UwModem::printOnLog(), receiving, rx_thread, transmitting, tx_queue_cv, and tx_thread.
Referenced by ~UwModemCSA().
transmittingData()
void UwModemCSA::transmittingData () private virtual
Method that detach a thread devoted to sending packets found in tx_queue.
References UwModem::DEBUG, UwModem::printOnLog(), startTx(), transmitting, UwModem::tx_queue, tx_queue_cv, and tx_queue_m.
Referenced by start().
Member Data Documentation
del_b
std::string UwModemCSA::del_b private
Referenced by findCommand().
del_e
std::string UwModemCSA::del_e private
Referenced by findCommand().
EPSILON_S
const double UwModemCSA::EPSILON_S = 0.01 static private
minimum time to wait before to schedule a new event in seconds
MAX_TX_STATUS_POLL
const size_t UwModemCSA::MAX_TX_STATUS_POLL = 20 static private
maximum number of time to poll the modem transmission status before to discard the transmitted packet
MODEM_TIMEOUT
const std::chrono::milliseconds UwModemCSA::MODEM_TIMEOUT static private
Initial value:
=
        std::chrono::milliseconds(210)
Maximum time to wait for modem to become ModemState::AVAILABLE
Referenced by startTx().
p_connector
std::unique_ptr<UwConnector> UwModemCSA::p_connector private
Pointer to Connector object that interfaces with the device
Referenced by command(), receivingData(), start(), startTx(), and stop().
receiving
std::atomic<bool> UwModemCSA::receiving private
Atomic boolean variable that controls the receiving looping thread
Referenced by receivingData(), start(), and stop().
rx_payload
std::string UwModemCSA::rx_payload private
String that is updated witn each new received messsage
Referenced by createRxPacket(), parseCommand(), and receivingData().
rx_thread
std::thread UwModemCSA::rx_thread private
Object with the rx thread
Referenced by start(), and stop().
status
ModemState UwModemCSA::status private
Variable holding the current status of the modem
Referenced by startRealRx(), and startTx().
status_cv
std::condition_variable UwModemCSA::status_cv private
Condition variable to wait for ModemState::AVAILABLE
Referenced by startRealRx(), and startTx().
status_m
std::mutex UwModemCSA::status_m private
Mutex associated with the state machine of the modem
Referenced by startRealRx(), and startTx().
transmitting
std::atomic<bool> UwModemCSA::transmitting private
Atomic boolean variable that controls the transmitting looping thread
Referenced by start(), stop(), and transmittingData().
tx_queue_cv
std::condition_variable UwModemCSA::tx_queue_cv private
Condition variable that is linked with the transmitting queue
Referenced by recv(), stop(), and transmittingData().
tx_queue_m
std::mutex UwModemCSA::tx_queue_m private
Mutex associated with the transmission queue
Referenced by recv(), and transmittingData().
tx_thread
std::thread UwModemCSA::tx_thread private
Object with the tx thread
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
DESERT_Framework/DESERT/physical/uwmodemcsa/uwmodemcsa.h
DESERT_Framework/DESERT/physical/uwmodemcsa/uwmodemcsa.cpp