DESERT: DESERT_Addons/uwmphy_modem/msocket.cpp File Reference
msocket.cpp File Reference
Implementation of the Msocket class.
Functions
void * read_process_msocket (void *pMsocket_me_)
Detailed Description
Implementation of the Msocket class.
Author
Riccardo Masiero
Federico Favaro
Version
2.0.0
Function Documentation
read_process_msocket()
void * read_process_msocket (void * pMsocket_me_)
Function to read from the modem via a TCP/IP connection (it must be called as a pure C function).
References UWMconnector::getDriverQueueLength(), Msocket::getSocket(), msgModem::msg_length, msgModem::msg_rx, and UWMconnector::queueMsg.
Referenced by Msocket::openConnection().