var files_dup =
[
    [ "clmsg-wakeUp-tone.cpp", "clmsg-wakeUp-tone_8cpp.html", "clmsg-wakeUp-tone_8cpp" ],
    [ "clmsg-wakeUp-tone.h", "clmsg-wakeUp-tone_8h.html", "clmsg-wakeUp-tone_8h" ],
    [ "frame-set.cpp", "frame-set_8cpp.html", "frame-set_8cpp" ],
    [ "frame-set.h", "frame-set_8h.html", "frame-set_8h" ],
    [ "hdr-uwal.cpp", "hdr-uwal_8cpp.html", "hdr-uwal_8cpp" ],
    [ "hdr-uwal.h", "hdr-uwal_8h.html", "hdr-uwal_8h" ],
    [ "application/uwcbr/initlib.cpp", "application_2uwcbr_2initlib_8cpp.html", "application_2uwcbr_2initlib_8cpp" ],
    [ "application/uwvbr/initlib.cpp", "application_2uwvbr_2initlib_8cpp.html", "application_2uwvbr_2initlib_8cpp" ],
    [ "application/uwApplication/initlib.cpp", "application_2uwApplication_2initlib_8cpp.html", "application_2uwApplication_2initlib_8cpp" ],
    [ "mobility/uwgmposition/initlib.cpp", "mobility_2uwgmposition_2initlib_8cpp.html", "mobility_2uwgmposition_2initlib_8cpp" ],
    [ "network/uwicrp/initlib.cpp", "network_2uwicrp_2initlib_8cpp.html", "network_2uwicrp_2initlib_8cpp" ],
    [ "network/uwip/initlib.cpp", "network_2uwip_2initlib_8cpp.html", "network_2uwip_2initlib_8cpp" ],
    [ "network/uwflooding/initlib.cpp", "network_2uwflooding_2initlib_8cpp.html", "network_2uwflooding_2initlib_8cpp" ],
    [ "network/uwstaticrouting/initlib.cpp", "network_2uwstaticrouting_2initlib_8cpp.html", "network_2uwstaticrouting_2initlib_8cpp" ],
    [ "network/uwsun/initlib.cpp", "network_2uwsun_2initlib_8cpp.html", "network_2uwsun_2initlib_8cpp" ],
    [ "transport/uwudp/initlib.cpp", "transport_2uwudp_2initlib_8cpp.html", "transport_2uwudp_2initlib_8cpp" ],
    [ "data_link/uw-csma-aloha/initlib.cpp", "data__link_2uw-csma-aloha_2initlib_8cpp.html", "data__link_2uw-csma-aloha_2initlib_8cpp" ],
    [ "data_link/uwdacap/initlib.cpp", "data__link_2uwdacap_2initlib_8cpp.html", "data__link_2uwdacap_2initlib_8cpp" ],
    [ "data_link/uwpolling/initlib.cpp", "data__link_2uwpolling_2initlib_8cpp.html", "data__link_2uwpolling_2initlib_8cpp" ],
    [ "data_link/uwaloha/initlib.cpp", "data__link_2uwaloha_2initlib_8cpp.html", "data__link_2uwaloha_2initlib_8cpp" ],
    [ "data_link/uw-t-lohi/initlib.cpp", "data__link_2uw-t-lohi_2initlib_8cpp.html", "data__link_2uw-t-lohi_2initlib_8cpp" ],
    [ "data_link/uwUFetch/initlib.cpp", "data__link_2uwUFetch_2initlib_8cpp.html", "data__link_2uwUFetch_2initlib_8cpp" ],
    [ "data_link/uwtdma/initlib.cpp", "data__link_2uwtdma_2initlib_8cpp.html", "data__link_2uwtdma_2initlib_8cpp" ],
    [ "data_link/uw-csma-aloha-trigger/initlib.cpp", "data__link_2uw-csma-aloha-trigger_2initlib_8cpp.html", "data__link_2uw-csma-aloha-trigger_2initlib_8cpp" ],
    [ "data_link/uwmll/initlib.cpp", "data__link_2uwmll_2initlib_8cpp.html", "data__link_2uwmll_2initlib_8cpp" ],
    [ "data_link/uwsr/initlib.cpp", "data__link_2uwsr_2initlib_8cpp.html", "data__link_2uwsr_2initlib_8cpp" ],
    [ "mobility/uwdriftposition/initlib.cpp", "mobility_2uwdriftposition_2initlib_8cpp.html", "mobility_2uwdriftposition_2initlib_8cpp" ],
    [ "mobility/uwsmposition/initlib.cpp", "mobility_2uwsmposition_2initlib_8cpp.html", "mobility_2uwsmposition_2initlib_8cpp" ],
    [ "interference/uwinterference/initlib.cpp", "interference_2uwinterference_2initlib_8cpp.html", "interference_2uwinterference_2initlib_8cpp" ],
    [ "physical/uw-al/initlib.cpp", "physical_2uw-al_2initlib_8cpp.html", "physical_2uw-al_2initlib_8cpp" ],
    [ "physical/uw-al/packer_common/initlib.cpp", "physical_2uw-al_2packer__common_2initlib_8cpp.html", "physical_2uw-al_2packer__common_2initlib_8cpp" ],
    [ "physical/uw-al/packer_mac/initlib.cpp", "physical_2uw-al_2packer__mac_2initlib_8cpp.html", "physical_2uw-al_2packer__mac_2initlib_8cpp" ],
    [ "physical/uwmphypatch/initlib.cpp", "physical_2uwmphypatch_2initlib_8cpp.html", "physical_2uwmphypatch_2initlib_8cpp" ],
    [ "physical/uwphysical/initlib.cpp", "physical_2uwphysical_2initlib_8cpp.html", "physical_2uwphysical_2initlib_8cpp" ],
    [ "physical/uwgainfromdb/initlib.cpp", "physical_2uwgainfromdb_2initlib_8cpp.html", "physical_2uwgainfromdb_2initlib_8cpp" ],
    [ "physical/uwphysicaldb/initlib.cpp", "physical_2uwphysicaldb_2initlib_8cpp.html", "physical_2uwphysicaldb_2initlib_8cpp" ],
    [ "physical/uwphysicalrogersmodel/initlib.cpp", "physical_2uwphysicalrogersmodel_2initlib_8cpp.html", "physical_2uwphysicalrogersmodel_2initlib_8cpp" ],
    [ "physical/uwhermesphy/initlib.cpp", "physical_2uwhermesphy_2initlib_8cpp.html", "physical_2uwhermesphy_2initlib_8cpp" ],
    [ "physical/uwoptical_phy/initlib.cpp", "physical_2uwoptical__phy_2initlib_8cpp.html", "physical_2uwoptical__phy_2initlib_8cpp" ],
    [ "propagation/uwoptical_propagation/initlib.cpp", "propagation_2uwoptical__propagation_2initlib_8cpp.html", "propagation_2uwoptical__propagation_2initlib_8cpp" ],
    [ "channel/uwoptical_channel/initlib.cpp", "channel_2uwoptical__channel_2initlib_8cpp.html", "channel_2uwoptical__channel_2initlib_8cpp" ],
    [ "physical/uwmodem/initlib.cpp", "physical_2uwmodem_2initlib_8cpp.html", "physical_2uwmodem_2initlib_8cpp" ],
    [ "physical/uwconnector/initlib.cpp", "physical_2uwconnector_2initlib_8cpp.html", "physical_2uwconnector_2initlib_8cpp" ],
    [ "physical/uwevologicss2cmodem/initlib.cpp", "physical_2uwevologicss2cmodem_2initlib_8cpp.html", "physical_2uwevologicss2cmodem_2initlib_8cpp" ],
    [ "interference-uw-WakeUp.cpp", "interference-uw-WakeUp_8cpp.html", "interference-uw-WakeUp_8cpp" ],
    [ "interference-uw-WakeUp.h", "interference-uw-WakeUp_8h.html", [
      [ "MInterfMivUwWakeUp", "classMInterfMivUwWakeUp.html", "classMInterfMivUwWakeUp" ]
    ] ],
    [ "marptable.cpp", "marptable_8cpp.html", null ],
    [ "marptable.h", "marptable_8h.html", "marptable_8h" ],
    [ "packer-common.cpp", "packer-common_8cpp.html", "packer-common_8cpp" ],
    [ "packer-common.h", "packer-common_8h.html", "packer-common_8h" ],
    [ "packer-mac.cpp", "packer-mac_8cpp.html", "packer-mac_8cpp" ],
    [ "packer-mac.h", "packer-mac_8h.html", [
      [ "packerMAC", "classpackerMAC.html", "classpackerMAC" ]
    ] ],
    [ "packer.cpp", "packer_8cpp.html", "packer_8cpp" ],
    [ "packer.h", "packer_8h.html", [
      [ "packer", "classpacker.html", "classpacker" ]
    ] ],
    [ "sun-hdr-ack.h", "sun-hdr-ack_8h.html", "sun-hdr-ack_8h" ],
    [ "sun-hdr-data.h", "sun-hdr-data_8h.html", "sun-hdr-data_8h" ],
    [ "sun-hdr-pathestablishment.h", "sun-hdr-pathestablishment_8h.html", "sun-hdr-pathestablishment_8h" ],
    [ "sun-hdr-probe.h", "sun-hdr-probe_8h.html", "sun-hdr-probe_8h" ],
    [ "sun-ipr-common-structures.h", "sun-ipr-common-structures_8h.html", "sun-ipr-common-structures_8h" ],
    [ "sun-ipr-node-ack.cpp", "sun-ipr-node-ack_8cpp.html", null ],
    [ "sun-ipr-node-buffermanager.cpp", "sun-ipr-node-buffermanager_8cpp.html", "sun-ipr-node-buffermanager_8cpp" ],
    [ "sun-ipr-node-data.cpp", "sun-ipr-node-data_8cpp.html", "sun-ipr-node-data_8cpp" ],
    [ "sun-ipr-node-loadmetric.cpp", "sun-ipr-node-loadmetric_8cpp.html", null ],
    [ "sun-ipr-node-pathest-answer.cpp", "sun-ipr-node-pathest-answer_8cpp.html", "sun-ipr-node-pathest-answer_8cpp" ],
    [ "sun-ipr-node-pathest-search.cpp", "sun-ipr-node-pathest-search_8cpp.html", "sun-ipr-node-pathest-search_8cpp" ],
    [ "sun-ipr-node.cpp", "sun-ipr-node_8cpp.html", "sun-ipr-node_8cpp" ],
    [ "sun-ipr-node.h", "sun-ipr-node_8h.html", [
      [ "SinkProbeTimer", "classSinkProbeTimer.html", "classSinkProbeTimer" ],
      [ "RemoveHopTableTimer", "classRemoveHopTableTimer.html", "classRemoveHopTableTimer" ],
      [ "BufferTimer", "classBufferTimer.html", "classBufferTimer" ],
      [ "SearchPathTimer", "classSearchPathTimer.html", "classSearchPathTimer" ],
      [ "SunIPRoutingNode", "classSunIPRoutingNode.html", "classSunIPRoutingNode" ]
    ] ],
    [ "sun-ipr-sink.cpp", "sun-ipr-sink_8cpp.html", "sun-ipr-sink_8cpp" ],
    [ "sun-ipr-sink.h", "sun-ipr-sink_8h.html", [
      [ "SunIPRoutingSink", "classSunIPRoutingSink.html", "classSunIPRoutingSink" ],
      [ "SendTimer", "classSunIPRoutingSink_1_1SendTimer.html", "classSunIPRoutingSink_1_1SendTimer" ]
    ] ],
    [ "sun-ipr.cpp", "sun-ipr_8cpp.html", "sun-ipr_8cpp" ],
    [ "uw-csma-aloha-trigger-node.cpp", "uw-csma-aloha-trigger-node_8cpp.html", "uw-csma-aloha-trigger-node_8cpp" ],
    [ "uw-csma-aloha-trigger-node.h", "uw-csma-aloha-trigger-node_8h.html", "uw-csma-aloha-trigger-node_8h" ],
    [ "uw-csma-aloha-trigger-sink.cpp", "uw-csma-aloha-trigger-sink_8cpp.html", "uw-csma-aloha-trigger-sink_8cpp" ],
    [ "uw-csma-aloha-trigger-sink.h", "uw-csma-aloha-trigger-sink_8h.html", "uw-csma-aloha-trigger-sink_8h" ],
    [ "uw-csma-aloha.cpp", "uw-csma-aloha_8cpp.html", "uw-csma-aloha_8cpp" ],
    [ "uw-csma-aloha.h", "uw-csma-aloha_8h.html", "uw-csma-aloha_8h" ],
    [ "uw-mac-DACAP-alter.cpp", "uw-mac-DACAP-alter_8cpp.html", "uw-mac-DACAP-alter_8cpp" ],
    [ "uw-mac-DACAP-alter.h", "uw-mac-DACAP-alter_8h.html", "uw-mac-DACAP-alter_8h" ],
    [ "uw-mac-DACAP-tracer.cpp", "uw-mac-DACAP-tracer_8cpp.html", "uw-mac-DACAP-tracer_8cpp" ],
    [ "uw-mac-TLohi-tracer.cpp", "uw-mac-TLohi-tracer_8cpp.html", "uw-mac-TLohi-tracer_8cpp" ],
    [ "uw-mac-TLohi.cpp", "uw-mac-TLohi_8cpp.html", "uw-mac-TLohi_8cpp" ],
    [ "uw-mac-TLohi.h", "uw-mac-TLohi_8h.html", "uw-mac-TLohi_8h" ],
    [ "uw-phy-WakeUp.cpp", "uw-phy-WakeUp_8cpp.html", "uw-phy-WakeUp_8cpp" ],
    [ "uw-phy-WakeUp.h", "uw-phy-WakeUp_8h.html", "uw-phy-WakeUp_8h" ],
    [ "uwal.cpp", "uwal_8cpp.html", "uwal_8cpp" ],
    [ "uwal.h", "uwal_8h.html", "uwal_8h" ],
    [ "uwaloha.cpp", "uwaloha_8cpp.html", "uwaloha_8cpp" ],
    [ "uwaloha.h", "uwaloha_8h.html", "uwaloha_8h" ],
    [ "uwApplication_cmn_header.h", "uwApplication__cmn__header_8h.html", "uwApplication__cmn__header_8h" ],
    [ "uwApplication_module.cpp", "uwApplication__module_8cpp.html", "uwApplication__module_8cpp" ],
    [ "uwApplication_module.h", "uwApplication__module_8h.html", "uwApplication__module_8h" ],
    [ "uwApplication_TCP_socket.cpp", "uwApplication__TCP__socket_8cpp.html", "uwApplication__TCP__socket_8cpp" ],
    [ "uwApplication_UDP_socket.cpp", "uwApplication__UDP__socket_8cpp.html", "uwApplication__UDP__socket_8cpp" ],
    [ "uwcbr-module.cpp", "uwcbr-module_8cpp.html", "uwcbr-module_8cpp" ],
    [ "uwcbr-module.h", "uwcbr-module_8h.html", "uwcbr-module_8h" ],
    [ "uwcbr-tracer.cpp", "uwcbr-tracer_8cpp.html", "uwcbr-tracer_8cpp" ],
    [ "uwconnector.h", "uwconnector_8h.html", [
      [ "UwConnector", "classUwConnector.html", "classUwConnector" ]
    ] ],
    [ "uwdriftposition.cpp", "uwdriftposition_8cpp.html", "uwdriftposition_8cpp" ],
    [ "uwdriftposition.h", "uwdriftposition_8h.html", [
      [ "UwDriftPosition", "classUwDriftPosition.html", "classUwDriftPosition" ]
    ] ],
    [ "uwevologicss2cmodem.cpp", "uwevologicss2cmodem_8cpp.html", "uwevologicss2cmodem_8cpp" ],
    [ "uwevologicss2cmodem.h", "uwevologicss2cmodem_8h.html", "uwevologicss2cmodem_8h" ],
    [ "uwflooding-hdr.h", "uwflooding-hdr_8h.html", "uwflooding-hdr_8h" ],
    [ "uwflooding.cpp", "uwflooding_8cpp.html", "uwflooding_8cpp" ],
    [ "uwflooding.h", "uwflooding_8h.html", "uwflooding_8h" ],
    [ "uwgainfromdb.cpp", "uwgainfromdb_8cpp.html", "uwgainfromdb_8cpp" ],
    [ "uwgainfromdb.h", "uwgainfromdb_8h.html", [
      [ "UnderwaterGainFromDb", "classUnderwaterGainFromDb.html", "classUnderwaterGainFromDb" ]
    ] ],
    [ "uwgmposition.cpp", "uwgmposition_8cpp.html", "uwgmposition_8cpp" ],
    [ "uwgmposition.h", "uwgmposition_8h.html", "uwgmposition_8h" ],
    [ "uwhermesphy.cpp", "uwhermesphy_8cpp.html", "uwhermesphy_8cpp" ],
    [ "uwhermesphy.h", "uwhermesphy_8h.html", "uwhermesphy_8h" ],
    [ "uwicrp-common.h", "uwicrp-common_8h.html", "uwicrp-common_8h" ],
    [ "uwicrp-hdr-ack.h", "uwicrp-hdr-ack_8h.html", "uwicrp-hdr-ack_8h" ],
    [ "uwicrp-hdr-data.h", "uwicrp-hdr-data_8h.html", "uwicrp-hdr-data_8h" ],
    [ "uwicrp-hdr-status.h", "uwicrp-hdr-status_8h.html", "uwicrp-hdr-status_8h" ],
    [ "uwicrp-module-node.cpp", "uwicrp-module-node_8cpp.html", "uwicrp-module-node_8cpp" ],
    [ "uwicrp-module-node.h", "uwicrp-module-node_8h.html", [
      [ "AckWaiting", "classAckWaiting.html", "classAckWaiting" ],
      [ "UwIcrpNode", "classUwIcrpNode.html", "classUwIcrpNode" ]
    ] ],
    [ "uwicrp-module-sink.cpp", "uwicrp-module-sink_8cpp.html", "uwicrp-module-sink_8cpp" ],
    [ "uwicrp-module-sink.h", "uwicrp-module-sink_8h.html", [
      [ "UwIcrpSink", "classUwIcrpSink.html", "classUwIcrpSink" ]
    ] ],
    [ "uwicrp.cpp", "uwicrp_8cpp.html", "uwicrp_8cpp" ],
    [ "uwinterference.cpp", "uwinterference_8cpp.html", "uwinterference_8cpp" ],
    [ "uwinterference.h", "uwinterference_8h.html", "uwinterference_8h" ],
    [ "UwInterferenceCollisionCounterInitTcl.cpp", "UwInterferenceCollisionCounterInitTcl_8cpp.html", "UwInterferenceCollisionCounterInitTcl_8cpp" ],
    [ "uwinterpreters2c.cpp", "uwinterpreters2c_8cpp.html", null ],
    [ "uwinterpreters2c.h", "uwinterpreters2c_8h.html", [
      [ "USBLInfo", "structUSBLInfo.html", "structUSBLInfo" ],
      [ "UwInterpreterS2C", "classUwInterpreterS2C.html", "classUwInterpreterS2C" ]
    ] ],
    [ "uwip-clmsg.cpp", "uwip-clmsg_8cpp.html", "uwip-clmsg_8cpp" ],
    [ "uwip-clmsg.h", "uwip-clmsg_8h.html", "uwip-clmsg_8h" ],
    [ "uwip-module.cpp", "uwip-module_8cpp.html", "uwip-module_8cpp" ],
    [ "uwip-module.h", "uwip-module_8h.html", "uwip-module_8h" ],
    [ "uwmll-module.cpp", "uwmll-module_8cpp.html", "uwmll-module_8cpp" ],
    [ "uwmll-module.h", "uwmll-module_8h.html", "uwmll-module_8h" ],
    [ "uwmodem.cpp", "uwmodem_8cpp.html", null ],
    [ "uwmodem.h", "uwmodem_8h.html", [
      [ "UwModem", "classUwModem.html", "classUwModem" ],
      [ "CheckTimer", "classCheckTimer.html", "classCheckTimer" ],
      [ "ModemEvent", "structModemEvent.html", "structModemEvent" ]
    ] ],
    [ "uwmphypatch.cpp", "uwmphypatch_8cpp.html", "uwmphypatch_8cpp" ],
    [ "uwmphypatch.h", "uwmphypatch_8h.html", [
      [ "UWMPhypatch", "classUWMPhypatch.html", "classUWMPhypatch" ]
    ] ],
    [ "uwoptical-channel.cpp", "uwoptical-channel_8cpp.html", "uwoptical-channel_8cpp" ],
    [ "uwoptical-channel.h", "uwoptical-channel_8h.html", [
      [ "UwOpticalChannel", "classUwOpticalChannel.html", "classUwOpticalChannel" ]
    ] ],
    [ "uwoptical-mpropagation.cpp", "uwoptical-mpropagation_8cpp.html", "uwoptical-mpropagation_8cpp" ],
    [ "uwoptical-mpropagation.h", "uwoptical-mpropagation_8h.html", "uwoptical-mpropagation_8h" ],
    [ "uwoptical-phy.cpp", "uwoptical-phy_8cpp.html", "uwoptical-phy_8cpp" ],
    [ "uwoptical-phy.h", "uwoptical-phy_8h.html", "uwoptical-phy_8h" ],
    [ "uwphysical.cpp", "uwphysical_8cpp.html", "uwphysical_8cpp" ],
    [ "uwphysical.h", "uwphysical_8h.html", [
      [ "UwPhysicalStats", "classUwPhysicalStats.html", "classUwPhysicalStats" ],
      [ "UnderwaterPhysical", "classUnderwaterPhysical.html", "classUnderwaterPhysical" ]
    ] ],
    [ "uwphysicaldb.cpp", "uwphysicaldb_8cpp.html", "uwphysicaldb_8cpp" ],
    [ "uwphysicaldb.h", "uwphysicaldb_8h.html", "uwphysicaldb_8h" ],
    [ "uwphysicalrogersmodel.cpp", "uwphysicalrogersmodel_8cpp.html", "uwphysicalrogersmodel_8cpp" ],
    [ "uwphysicalrogersmodel.h", "uwphysicalrogersmodel_8h.html", [
      [ "UnderwaterPhysicalRogersModel", "classUnderwaterPhysicalRogersModel.html", "classUnderwaterPhysicalRogersModel" ]
    ] ],
    [ "uwpolling_AUV.cpp", "uwpolling__AUV_8cpp.html", "uwpolling__AUV_8cpp" ],
    [ "uwpolling_AUV.h", "uwpolling__AUV_8h.html", "uwpolling__AUV_8h" ],
    [ "uwpolling_cmn_hdr.h", "uwpolling__cmn__hdr_8h.html", "uwpolling__cmn__hdr_8h" ],
    [ "uwpolling_NODE.cpp", "uwpolling__NODE_8cpp.html", "uwpolling__NODE_8cpp" ],
    [ "uwpolling_NODE.h", "uwpolling__NODE_8h.html", "uwpolling__NODE_8h" ],
    [ "uwpolling_SINK.cpp", "uwpolling__SINK_8cpp.html", "uwpolling__SINK_8cpp" ],
    [ "uwpolling_SINK.h", "uwpolling__SINK_8h.html", "uwpolling__SINK_8h" ],
    [ "uwserial.cpp", "uwserial_8cpp.html", null ],
    [ "uwserial.h", "uwserial_8h.html", [
      [ "UwSerial", "classUwSerial.html", "classUwSerial" ]
    ] ],
    [ "uwsmposition.cpp", "uwsmposition_8cpp.html", "uwsmposition_8cpp" ],
    [ "uwsmposition.h", "uwsmposition_8h.html", "uwsmposition_8h" ],
    [ "uwsocket.cpp", "uwsocket_8cpp.html", null ],
    [ "uwsocket.h", "uwsocket_8h.html", "uwsocket_8h" ],
    [ "uwsr.cpp", "uwsr_8cpp.html", "uwsr_8cpp" ],
    [ "uwsr.h", "uwsr_8h.html", "uwsr_8h" ],
    [ "uwstaticrouting.cpp", "uwstaticrouting_8cpp.html", "uwstaticrouting_8cpp" ],
    [ "uwstaticrouting.h", "uwstaticrouting_8h.html", "uwstaticrouting_8h" ],
    [ "uwtdma.cpp", "uwtdma_8cpp.html", "uwtdma_8cpp" ],
    [ "uwtdma.h", "uwtdma_8h.html", "uwtdma_8h" ],
    [ "uwudp-module.cpp", "uwudp-module_8cpp.html", "uwudp-module_8cpp" ],
    [ "uwudp-module.h", "uwudp-module_8h.html", "uwudp-module_8h" ],
    [ "uwUFetch_AUV.cpp", "uwUFetch__AUV_8cpp.html", "uwUFetch__AUV_8cpp" ],
    [ "uwUFetch_AUV.h", "uwUFetch__AUV_8h.html", "uwUFetch__AUV_8h" ],
    [ "uwUFetch_AUV_mod_1.cpp", "uwUFetch__AUV__mod__1_8cpp.html", "uwUFetch__AUV__mod__1_8cpp" ],
    [ "uwUFetch_AUV_mod_2.cpp", "uwUFetch__AUV__mod__2_8cpp.html", null ],
    [ "uwUFetch_cmn_hdr.h", "uwUFetch__cmn__hdr_8h.html", "uwUFetch__cmn__hdr_8h" ],
    [ "uwUFetch_NODE.h", "uwUFetch__NODE_8h.html", "uwUFetch__NODE_8h" ],
    [ "uwUFetch_NODE_HEADNODE.cpp", "uwUFetch__NODE__HEADNODE_8cpp.html", null ],
    [ "uwUFetch_NODE_HEADNODE_mod_1.cpp", "uwUFetch__NODE__HEADNODE__mod__1_8cpp.html", null ],
    [ "uwUFetch_NODE_HEADNODE_mod_2.cpp", "uwUFetch__NODE__HEADNODE__mod__2_8cpp.html", null ],
    [ "uwUFetch_NODE_SENSOR.cpp", "uwUFetch__NODE__SENSOR_8cpp.html", "uwUFetch__NODE__SENSOR_8cpp" ],
    [ "uwvbr-module.cpp", "uwvbr-module_8cpp.html", "uwvbr-module_8cpp" ],
    [ "uwvbr-module.h", "uwvbr-module_8h.html", "uwvbr-module_8h" ],
    [ "wake-up-pkt-hdr.h", "wake-up-pkt-hdr_8h.html", "wake-up-pkt-hdr_8h" ]
];