DESERT: hdr_POLL_UFETCH Struct Reference
hdr_POLL_UFETCH Struct Reference
#include <uwUFetch_cmn_hdr.h>
Public Member Functions
int & num_DATA_pcks_MAX_rx ()
int & mac_addr_Node_polled ()
Static Public Member Functions
static int & offset ()
static struct hdr_POLL_UFETCH * access (const Packet *p)
Public Attributes
int num_DATA_pcks_MAX_rx_
int mac_addr_Node_polled_
Static Public Attributes
static int offset_ = 0
Detailed Description
Content header of POLL packet
Member Function Documentation
access()
static struct hdr_POLL_UFETCH * hdr_POLL_UFETCH::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
mac_addr_Node_polled()
int & hdr_POLL_UFETCH::mac_addr_Node_polled () inline
Reference to mac_addr_Node_polled_ variable
Returns
int& mac_addr_Node_polled_
References mac_addr_Node_polled_.
Referenced by uwUFetch_NODE::state_POLL_tx().
num_DATA_pcks_MAX_rx()
int & hdr_POLL_UFETCH::num_DATA_pcks_MAX_rx () inline
Reference to num_DATA_pcks_MAX_rx variable
Returns
int& num_DATA_pcks_MAX_rx_
References num_DATA_pcks_MAX_rx_.
Referenced by uwUFetch_NODE::Phy2MacEndRx(), uwUFetch_NODE::POLL_rx(), and uwUFetch_NODE::state_POLL_tx().
offset()
static int & hdr_POLL_UFETCH::offset () inline static
Reference to the offset variable
References offset_.
Member Data Documentation
mac_addr_Node_polled_
int hdr_POLL_UFETCH::mac_addr_Node_polled_
Mac address of the NODE that the HN has polled and from which it want to receive a data packet
Referenced by mac_addr_Node_polled(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
num_DATA_pcks_MAX_rx_
int hdr_POLL_UFETCH::num_DATA_pcks_MAX_rx_
Maximum number of DATA packet that HN want to receive from the specific node that is being to poll
Referenced by num_DATA_pcks_MAX_rx(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
offset_
int hdr_POLL_UFETCH::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uwUFetch/uwUFetch_cmn_hdr.h
DESERT_Framework/DESERT/data_link/uwUFetch/initlib.cpp