DESERT: hdr_tokenbus Struct Reference
hdr_tokenbus Struct Reference
#include <uwtokenbus_hdr.h>
Public Member Functions
tokenid_t & tokenId ()
size_t getSize () const
Static Public Member Functions
static int & offset ()
static struct hdr_tokenbus * access (const Packet *p)
Public Attributes
tokenid_t token_id_
Static Public Attributes
static int offset_ = 0
Detailed Description
Header of the token bus protocol
Member Function Documentation
access()
static struct hdr_tokenbus * hdr_tokenbus::access (const Packet * p) inline static
Returns a pointer to the tokenbus header of the packet p
Parameters
p Packet
Returns
a pointer to the tokenbus header of the packet p
References access(), and offset_.
Referenced by access().
getSize()
size_t hdr_tokenbus::getSize () const inline
Returns the size of this header
Returns
the size of this header
Referenced by UwTokenBus::initPkt(), UwTokenBus::sendToken(), and UwRangingTokenBus::sendToken().
offset()
static int & hdr_tokenbus::offset () inline static
Returns a reference to the offset variable
Returns
a reference to the offset variable
References offset_.
tokenId()
tokenid_t & hdr_tokenbus::tokenId () inline
Returns a reference to the token_id variable
Returns
a reference to the token_id variable
References token_id_.
Referenced by UwTokenBus::Mac2PhyStartTx(), UwTokenBus::Phy2MacEndRx(), UwRangingTokenBus::Phy2MacEndRx(), UwTokenBus::sendToken(), UwRangingTokenBus::sendToken(), and UwTokenBus::validToken().
Member Data Documentation
offset_
int hdr_tokenbus::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
token_id_
tokenid_t hdr_tokenbus::token_id_
progressive token id, indicates which node has the token
Referenced by tokenId().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uwtokenbus/uwtokenbus_hdr.h
DESERT_Framework/DESERT/data_link/uwtokenbus/initlib.cpp