DESERT: hdr_sun_path_est Struct Reference
hdr_sun_path_est Struct Reference
#include <sun-hdr-pathestablishment.h>
Public Member Functions
uint8_t & sinkAssociated ()
packet_path_est & ptype ()
uint8_t * list_of_hops ()
u_int8_t & list_of_hops_length ()
int8_t & pointer ()
float & quality ()
Static Public Member Functions
static int & offset ()
static struct hdr_sun_path_est * access (const Packet *p)
Public Attributes
uint8_t sink_associated_
packet_path_est ptype_
uint8_t list_of_hops_ [MAX_HOP_NUMBER]
int8_t pointer_to_list_of_hops_
uint8_t list_of_hops_length_
float quality_
Static Public Attributes
static int offset_ = 0
Detailed Description
hdr_sun_path_est describes path establishment packets used by UWSUN
Member Function Documentation
access()
static struct hdr_sun_path_est * hdr_sun_path_est::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
list_of_hops()
uint8_t * hdr_sun_path_est::list_of_hops () inline
Pointer to the list_of_hops_ variable
References list_of_hops_.
Referenced by SunIPRoutingNode::addMyIpInList(), SunIPRoutingNode::createRouteError(), SunIPRoutingNode::evaluatePath(), SunIPRoutingNode::initPktPathEstAnswer(), SunIPRoutingNode::initPktPathEstSearch(), SunIPRoutingNode::isMyIpInList(), SunIPRoutingNode::sendRouteBack(), and SunIPRoutingNode::sendRouteErrorBack().
list_of_hops_length()
u_int8_t & hdr_sun_path_est::list_of_hops_length () inline
Reference to the list_of_hops_length_ variable
References list_of_hops_length_.
Referenced by SunIPRoutingNode::addMyIpInList(), SunIPRoutingNode::answerPath(), SunIPRoutingNode::createRouteError(), SunIPRoutingNode::evaluatePath(), SunIPRoutingNode::initPktPathEstAnswer(), SunIPRoutingNode::initPktPathEstSearch(), SunIPRoutingNode::isMyIpInList(), SunIPRoutingNode::sendRouteBack(), and SunIPRoutingNode::sendRouteErrorBack().
offset()
static int & hdr_sun_path_est::offset () inline static
Reference to the offset_ variable
References offset_.
pointer()
int8_t & hdr_sun_path_est::pointer () inline
Reference to the pointer_to_list_of_hops_ variable
References pointer_to_list_of_hops_.
Referenced by SunIPRoutingNode::addMyIpInList(), SunIPRoutingNode::createRouteError(), SunIPRoutingNode::initPktPathEstAnswer(), SunIPRoutingNode::sendRouteBack(), and SunIPRoutingNode::sendRouteErrorBack().
ptype()
packet_path_est & hdr_sun_path_est::ptype () inline
Reference to the ptype_ variable
References ptype_.
Referenced by SunIPRoutingNode::createRouteError(), SunIPRoutingNode::initPktPathEstAnswer(), SunIPRoutingNode::initPktPathEstSearch(), SunIPRoutingNode::recv(), and SunIPRoutingNode::sendRouteBack().
quality()
float & hdr_sun_path_est::quality () inline
Reference to the quality_ variable
References quality_.
Referenced by SunIPRoutingNode::evaluatePath(), SunIPRoutingNode::initPktPathEstAnswer(), SunIPRoutingNode::initPktPathEstSearch(), SunIPRoutingNode::sendRouteBack(), and SunIPRoutingNode::updateQuality().
sinkAssociated()
uint8_t & hdr_sun_path_est::sinkAssociated () inline
Reference to the sink_associated_ variable
References sink_associated_.
Referenced by SunIPRoutingNode::evaluatePath(), SunIPRoutingNode::initPktPathEstAnswer(), and SunIPRoutingNode::sendRouteBack().
Member Data Documentation
list_of_hops_
uint8_t hdr_sun_path_est::list_of_hops_[MAX_HOP_NUMBER]
List of IPs saved in the header
Referenced by list_of_hops().
list_of_hops_length_
uint8_t hdr_sun_path_est::list_of_hops_length_
Current number of IPs stored in the header
Referenced by list_of_hops_length().
offset_
int hdr_sun_path_est::offset_ = 0 static
Required by the PacketHeaderManager
Offset used to access in hdr_sun_path_est packets header.
Referenced by access(), and offset().
pointer_to_list_of_hops_
int8_t hdr_sun_path_est::pointer_to_list_of_hops_
Pointer used to keep track of the last IPs processed
Referenced by pointer().
ptype_
packet_path_est hdr_sun_path_est::ptype_
Idientifier of the packet type: PATH_SEARCH, PATH_ANSWER or PATH_ERROR
Referenced by ptype(), and SunIPRoutingNode::replyPathEstSearch().
quality_
float hdr_sun_path_est::quality_
Used to save information about the "quality" of the metric used
Referenced by quality().
sink_associated_
uint8_t hdr_sun_path_est::sink_associated_
IP of the sink associated with the packet
Referenced by sinkAssociated().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/network/uwsun/sun-hdr-pathestablishment.h
DESERT_Framework/DESERT/network/uwsun/sun-ipr.cpp