DESERT: hdr_uwROV_ctr Struct Reference
hdr_uwROV_ctr Struct Reference
#include <uwrov-packet.h>
Public Member Functions
float & x ()
float & y ()
float & z ()
float & speed ()
double & sn ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwROV_ctr * access (const Packet *p)
Public Attributes
float x_
float y_
float z_
float speed_
double sn_
Static Public Attributes
static int offset_
Detailed Description
hdr_uwROV_ctr describes UWROV_ctr packets for controlling the ROV.
Member Function Documentation
access()
static struct hdr_uwROV_ctr * hdr_uwROV_ctr::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
offset()
static int & hdr_uwROV_ctr::offset () inline static
Reference to the offset_ variable.
References offset_.
sn()
double & hdr_uwROV_ctr::sn () inline
References sn_.
Referenced by UwROVCtrModule::initPkt(), and UwROVModule::recv().
speed()
float & hdr_uwROV_ctr::speed () inline
References speed_.
Referenced by UwROVCtrModule::initPkt(), and UwROVModule::recv().
x()
float & hdr_uwROV_ctr::x () inline
References x_.
Referenced by UwROVCtrModule::initPkt(), and UwROVModule::recv().
y()
float & hdr_uwROV_ctr::y () inline
References y_.
Referenced by UwROVCtrModule::initPkt(), and UwROVModule::recv().
z()
float & hdr_uwROV_ctr::z () inline
References z_.
Referenced by UwROVCtrModule::initPkt(), and UwROVModule::recv().
Member Data Documentation
offset_
int hdr_uwROV_ctr::offset_ static
Required by the PacketHeaderManager.
Offset used to access in hdr_uwROV packets header.
Referenced by access(), and offset().
sn_
double hdr_uwROV_ctr::sn_
Referenced by sn().
speed_
float hdr_uwROV_ctr::speed_
Referenced by speed().
x_
float hdr_uwROV_ctr::x_
Referenced by x().
y_
float hdr_uwROV_ctr::y_
Referenced by y().
z_
float hdr_uwROV_ctr::z_
Referenced by z().
The documentation for this struct was generated from the following files:
DESERT_Addons/uwrov/uwrov-packet.h
DESERT_Addons/uwrov/uwrov-module.cc