DESERT: hdr_uwudp Struct Reference
hdr_uwudp Struct Reference
#include <uwudp-module.h>
Public Member Functions
uint8_t & sport ()
uint8_t & dport ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwudp * access (const Packet *p)
Public Attributes
uint8_t sport_
uint8_t dport_
Static Public Attributes
static int offset_ = 0
Detailed Description
hdr_uwudp describes UWUDP packets.
Member Function Documentation
access()
static struct hdr_uwudp * hdr_uwudp::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access(), UwCbrModule::initPkt(), and UwVbrModule::initPkt().
dport()
uint8_t & hdr_uwudp::dport () inline
Reference to the dport_ variable.
References dport_.
Referenced by UwCbrModule::initPkt(), UwVbrModule::initPkt(), packerUWUDP::printMyHdrFields(), UwUdp::recv(), uwApplicationModule::transmit(), and packerUWUDP::unpackMyHdr().
offset()
static int & hdr_uwudp::offset () inline static
Reference to the offset_ variable.
References offset_.
sport()
uint8_t & hdr_uwudp::sport () inline
Reference to the sport_ variable.
References sport_.
Referenced by packerUWUDP::printMyHdrFields(), UwUdp::recv(), and packerUWUDP::unpackMyHdr().
Member Data Documentation
dport_
uint8_t hdr_uwudp::dport_
Destination port number.
Referenced by dport(), packerUWUDP::packMyHdr(), and packerUWUDP::unpackMyHdr().
offset_
int hdr_uwudp::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
sport_
uint8_t hdr_uwudp::sport_
Source port number.
Referenced by packerUWUDP::packMyHdr(), sport(), and packerUWUDP::unpackMyHdr().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/transport/uwudp/uwudp-module.h
DESERT_Framework/DESERT/transport/uwudp/uwudp-module.cpp