DESERT: hdr_uwcbr Struct Reference
hdr_uwcbr Struct Reference
#include <uwcbr-module.h>
Public Member Functions
uint16_t & sn ()
bool & rftt_valid ()
char & priority ()
float & rftt ()
uint16_t & traffic_type ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwcbr * access (const Packet *p)
Public Attributes
uint16_t sn_
float rftt_
bool rftt_valid_
char priority_
uint16_t traffic_type_
Static Public Attributes
static int offset_
Detailed Description
hdr_uwcbr describes UWCBR packets.
Member Function Documentation
access()
static struct hdr_uwcbr * hdr_uwcbr::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
offset()
static int & hdr_uwcbr::offset () inline static
Reference to the offset_ variable.
References offset_.
priority()
char & hdr_uwcbr::priority () inline
Reference to the priority_ variable.
References priority_.
Referenced by UwMultiTrafficRangeCtr::checkRange(), UwCbrModule::initPkt(), UwROVModule::initPkt(), UwTDMA::recvFromUpperLayers(), UwTokenBus::recvFromUpperLayers(), UwCbrModule::sendPktHighPriority(), and UwCbrModule::sendPktLowPriority().
rftt()
float & hdr_uwcbr::rftt () inline
Reference to the rftt_ variable.
References rftt_.
Referenced by UwCbrModule::initPkt(), packerUWCBR::printMyHdrFields(), and UwCbrModule::recv().
rftt_valid()
bool & hdr_uwcbr::rftt_valid () inline
Reference to the rftt_valid_ variable.
References rftt_valid_.
Referenced by UwCbrModule::initPkt(), packerUWCBR::printMyHdrFields(), and UwCbrModule::recv().
sn()
uint16_t & hdr_uwcbr::sn () inline
Reference to the sn_ variable.
References sn_.
Referenced by SunIPRoutingNode::bufferManager(), UWCbrTracer::format(), UwCbrModule::initPkt(), uwUFetch_NODE::Phy2MacEndRx_HN_without(), uwUFetch_AUV::Phy2MacEndRx_without(), packerUWCBR::printMyHdrFields(), UwTrackerModule::printReceivedPacket(), UwCbrModule::printReceivedPacket(), SunIPRoutingNode::recv(), UwCbrModule::recv(), uwUFetch_NODE::recvFromUpperLayers(), SunIPRoutingNode::sendBackAck(), SunIPRoutingSink::sendBackAck(), UwCbrModule::sendPkt(), UwCbrModule::sendPktHighPriority(), UwCbrModule::sendPktLowPriority(), uwUFetch_NODE::state_DATA_HN_first_tx_without(), uwUFetch_NODE::state_DATA_HN_tx_without(), uwUFetch_NODE::state_DATA_NODE_first_tx(), uwUFetch_NODE::state_DATA_NODE_tx(), SunIPRoutingNode::tracePacket(), and SunIPRoutingSink::tracePacket().
traffic_type()
uint16_t & hdr_uwcbr::traffic_type () inline
Reference to the rftt_ variable.
References traffic_type_.
Referenced by UwFloodingSec::getTTL(), UwFlooding::getTTL(), UwCbrModule::initPkt(), packerUWCBR::printMyHdrFields(), UwMultiTrafficControl::recv(), UwMultiPhyControl::recvFromUpperLayers(), and UwMultiTrafficControl::recvFromUpperLayers().
Member Data Documentation
offset_
int hdr_uwcbr::offset_ static
Required by the PacketHeaderManager.
Offset used to access in hdr_uwcbr packets header.
Referenced by access(), and offset().
priority_
char hdr_uwcbr::priority_
Priority flag: 1 means high priority, 0 normal priority.
Referenced by priority().
rftt_
float hdr_uwcbr::rftt_
Forward Trip Time of the packet.
Referenced by packerUWCBR::packMyHdr(), rftt(), and packerUWCBR::unpackMyHdr().
rftt_valid_
bool hdr_uwcbr::rftt_valid_
Flag used to set the validity of the fft field.
Referenced by UWCbrTracer::format(), packerUWCBR::packMyHdr(), rftt_valid(), and packerUWCBR::unpackMyHdr().
sn_
uint16_t hdr_uwcbr::sn_
Serial number of the packet.
Referenced by packerUWCBR::packMyHdr(), Uwpolling_AUV::recvFromUpperLayers(), Uwpolling_NODE::recvFromUpperLayers(), sn(), Uwpolling_AUV::stateRxData(), Uwpolling_SINK::stateRxData(), Uwpolling_NODE::stateTxData(), and packerUWCBR::unpackMyHdr().
traffic_type_
uint16_t hdr_uwcbr::traffic_type_
Traffic type: (video, audio, image, etc..) meaning left to the user
Referenced by packerUWCBR::packMyHdr(), traffic_type(), and packerUWCBR::unpackMyHdr().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/application/uwcbr/uwcbr-module.h
DESERT_Framework/DESERT/application/uwcbr/uwcbr-module.cpp