DESERT: hdr_uwTracker Struct Reference
hdr_uwTracker Struct Reference
#include <uwtracker-packet.h>
Public Member Functions
float & timestamp ()
float & x ()
float & y ()
float & z ()
float & speed ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwTracker * access (const Packet *p)
Public Attributes
float timestamp_
float x_
float y_
float z_
float speed_
Static Public Attributes
static int offset_
Detailed Description
hdr_uwROV_ctr describes UWROV_ctr packets for controlling the ROV.
Member Function Documentation
access()
static struct hdr_uwTracker * hdr_uwTracker::access (const Packet * p) inline static
static method to access the packet header
References access(), and offset_.
Referenced by access().
offset()
static int & hdr_uwTracker::offset () inline static
Reference to the offset_ variable.
References offset_.
speed()
float & hdr_uwTracker::speed () inline
Reference to the speed variable.
References speed_.
Referenced by UwTrackerModule::initPkt(), UwTrackerModule::printReceivedPacket(), and UwTrackerModule::updateTrackMeasure().
timestamp()
float & hdr_uwTracker::timestamp () inline
Reference to the timestamp variable.
References timestamp_.
Referenced by UwTrackerModule::printReceivedPacket(), and UwTrackerModule::updateTrackMeasure().
x()
float & hdr_uwTracker::x () inline
Reference to the x variable.
References x_.
Referenced by UwTrackerModule::initPkt(), UwSCFTrackerModule::initPkt(), UwTrackerModule::printReceivedPacket(), UwSCFTrackerModule::sendPkt(), UwTrackerModule::sendPkt(), UwSCFTrackerModule::updateMineRemove(), and UwTrackerModule::updateTrackMeasure().
y()
float & hdr_uwTracker::y () inline
Reference to the y variable.
References y_.
Referenced by UwTrackerModule::initPkt(), UwSCFTrackerModule::initPkt(), UwTrackerModule::printReceivedPacket(), UwSCFTrackerModule::sendPkt(), UwTrackerModule::sendPkt(), UwSCFTrackerModule::updateMineRemove(), and UwTrackerModule::updateTrackMeasure().
z()
float & hdr_uwTracker::z () inline
Reference to the z variable.
References z_.
Referenced by UwTrackerModule::initPkt(), UwSCFTrackerModule::initPkt(), UwTrackerModule::printReceivedPacket(), UwSCFTrackerModule::sendPkt(), UwTrackerModule::sendPkt(), UwSCFTrackerModule::updateMineRemove(), and UwTrackerModule::updateTrackMeasure().
Member Data Documentation
offset_
int hdr_uwTracker::offset_ static
Required by the PacketHeaderManager.
Offset used to access in hdr_uwTracker packets header.
Referenced by access(), and offset().
speed_
float hdr_uwTracker::speed_
magnitude of the relative speed (from Doppler)
Referenced by speed().
timestamp_
float hdr_uwTracker::timestamp_
timestamp when the target was tracked
Referenced by timestamp().
x_
float hdr_uwTracker::x_
x
Referenced by x().
y_
float hdr_uwTracker::y_
y
Referenced by y().
z_
float hdr_uwTracker::z_
z
Referenced by z().
The documentation for this struct was generated from the following files:
DESERT_Addons/uwtracker/uwtracker-packet.h
DESERT_Addons/uwtracker/uwtracker-module.cpp