DESERT: hdr_ca_CTS Struct Reference
hdr_ca_CTS Struct Reference
#include <uw-csma-ca-hdrs.h>
Public Member Functions
uint8_t & get_tx_time ()
void set_tx_time (int time)
Static Public Member Functions
static int & get_offset ()
static struct hdr_ca_CTS * access (const Packet *p)
Static Public Attributes
static int offset_ = 0
Private Attributes
uint8_t tx_time
Member Function Documentation
access()
static struct hdr_ca_CTS * hdr_ca_CTS::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
get_offset()
static int & hdr_ca_CTS::get_offset () inline static
References offset_.
get_tx_time()
uint8_t & hdr_ca_CTS::get_tx_time () inline
References tx_time.
Referenced by packerUwCsmaCa::packMyHdr(), packerUwCsmaCa::printMyHdrFields(), CsmaCa::stateRxCTS(), and packerUwCsmaCa::unpackMyHdr().
set_tx_time()
void hdr_ca_CTS::set_tx_time (int time) inline
References tx_time.
Member Data Documentation
offset_
int hdr_ca_CTS::offset_ = 0 static
Referenced by access(), and get_offset().
tx_time
uint8_t hdr_ca_CTS::tx_time private
Referenced by get_tx_time(), and set_tx_time().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uw-csma-ca/uw-csma-ca-hdrs.h
DESERT_Framework/DESERT/data_link/uw-csma-ca/initlib.cpp