DESERT: hdr_CTS_UFETCH Struct Reference
hdr_CTS_UFETCH Struct Reference
#include <uwUFetch_cmn_hdr.h>
Public Member Functions
int & num_DATA_pcks_MAX_rx ()
int & mac_addr_HN_ctsed ()
Static Public Member Functions
static int & offset ()
static hdr_CTS_UFETCH * access (const Packet *p)
Public Attributes
int num_DATA_pcks_MAX_rx_
int mac_addr_HN_ctsed_
Static Public Attributes
static int offset_ = 0
Detailed Description
Content header of CTS packet
Member Function Documentation
access()
static hdr_CTS_UFETCH * hdr_CTS_UFETCH::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
mac_addr_HN_ctsed()
int & hdr_CTS_UFETCH::mac_addr_HN_ctsed () inline
Reference to the mac_addr_HN_ctsed_ variable
Returns
int& mac_addr_HN_ctsed_
References mac_addr_HN_ctsed_.
Referenced by uwUFetch_AUV::state_CTS_tx().
num_DATA_pcks_MAX_rx()
int & hdr_CTS_UFETCH::num_DATA_pcks_MAX_rx () inline
Reference to the num_DATA_pcks_MAX_rx_ variable
Returns
int& num_DATA_pcks_MAX_rx_
References num_DATA_pcks_MAX_rx_.
Referenced by uwUFetch_NODE::CTS_rx(), and uwUFetch_AUV::state_CTS_tx().
offset()
static int & hdr_CTS_UFETCH::offset () inline static
Reference to the offset variable
References offset_.
Member Data Documentation
mac_addr_HN_ctsed_
int hdr_CTS_UFETCH::mac_addr_HN_ctsed_
Mac address of the HN from which the AUV want to receive the DATA packets
Referenced by mac_addr_HN_ctsed(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
num_DATA_pcks_MAX_rx_
int hdr_CTS_UFETCH::num_DATA_pcks_MAX_rx_
maximum number of packets that AUV want receive from HN
Referenced by num_DATA_pcks_MAX_rx(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
offset_
int hdr_CTS_UFETCH::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uwUFetch/uwUFetch_cmn_hdr.h
DESERT_Framework/DESERT/data_link/uwUFetch/initlib.cpp