DESERT: hdr_sun_data Struct Reference
hdr_sun_data Struct Reference
#include <sun-hdr-data.h>
Public Member Functions
uint8_t * list_of_hops ()
u_int8_t & list_of_hops_length ()
int8_t & pointer ()
Static Public Member Functions
static int & offset ()
static struct hdr_sun_data * access (const Packet *p)
Public Attributes
uint8_t list_of_hops_ [MAX_HOP_NUMBER]
int8_t pointer_to_list_of_hops_
u_int8_t list_of_hops_length_
Static Public Attributes
static int offset_
Detailed Description
hdr_sun_data describes data packets used by UWSUN
Member Function Documentation
access()
static struct hdr_sun_data * hdr_sun_data::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
list_of_hops()
uint8_t * hdr_sun_data::list_of_hops () inline
Pointer to the list_of_hops_ variable
References list_of_hops_.
Referenced by SunIPRoutingNode::bufferManager(), SunIPRoutingNode::createRouteError(), SunIPRoutingNode::forwardDataPacket(), SunIPRoutingNode::initPktDataPacket(), SunIPRoutingNode::recv(), and SunIPRoutingSink::writePathInTrace().
list_of_hops_length()
u_int8_t & hdr_sun_data::list_of_hops_length () inline
Reference to the list_of_hops_length_ variable
References list_of_hops_length_.
Referenced by SunIPRoutingNode::bufferManager(), SunIPRoutingNode::forwardDataPacket(), SunIPRoutingNode::initPktDataPacket(), SunIPRoutingNode::recv(), SunIPRoutingSink::recv(), and SunIPRoutingSink::writePathInTrace().
offset()
static int & hdr_sun_data::offset () inline static
Reference to the offset_ variable
References offset_.
pointer()
int8_t & hdr_sun_data::pointer () inline
Reference to the pointer_to_list_of_hops_ variable
References pointer_to_list_of_hops_.
Referenced by SunIPRoutingNode::createRouteError(), SunIPRoutingNode::forwardDataPacket(), and SunIPRoutingNode::initPktDataPacket().
Member Data Documentation
list_of_hops_
uint8_t hdr_sun_data::list_of_hops_[MAX_HOP_NUMBER]
List of IPs saved in the header
Referenced by list_of_hops().
list_of_hops_length_
u_int8_t hdr_sun_data::list_of_hops_length_
Current number of IPs stored in the header
Referenced by list_of_hops_length().
offset_
int hdr_sun_data::offset_ static
Initial value:
=
        0
Required by the PacketHeaderManager
Offset used to access in hdr_sun_data packets header.
Referenced by access(), and offset().
pointer_to_list_of_hops_
int8_t hdr_sun_data::pointer_to_list_of_hops_
Pointer used to keep track of the last IPs processed
Referenced by pointer().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/network/uwsun/sun-hdr-data.h
DESERT_Framework/DESERT/network/uwsun/sun-ipr.cpp