DESERT: hdr_uwSCFTracker Struct Reference
hdr_uwSCFTracker Struct Reference
#include <uwsc-tracker-follower-packet.h>
Public Member Functions
float & timestamp ()
float & x ()
float & y ()
float & z ()
bool & mine_remove ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwSCFTracker * access (const Packet *p)
Public Attributes
float timestamp_
float x_
float y_
float z_
bool mine_remove_
Static Public Attributes
static int offset_
Detailed Description
hdr_uwSCFTracker describes the position and status of the current detected mine.
Member Function Documentation
access()
static struct hdr_uwSCFTracker * hdr_uwSCFTracker::access (const Packet * p) inline static
static method to access the packet header
References access(), and offset_.
Referenced by access().
mine_remove()
bool & hdr_uwSCFTracker::mine_remove () inline
Reference to the speed variable.
References mine_remove_.
Referenced by UwSCTrackerModule::recv(), UwSCFTrackerModule::sendPkt(), and UwSCFTrackerModule::updateMineRemove().
offset()
static int & hdr_uwSCFTracker::offset () inline static
Reference to the offset_ variable.
References offset_.
timestamp()
float & hdr_uwSCFTracker::timestamp () inline
Reference to the timestamp variable.
References timestamp_.
Referenced by UwSCFTrackerModule::updateTrackPosition().
x()
float & hdr_uwSCFTracker::x () inline
Reference to the x variable.
References x_.
Referenced by UwSCFTrackerModule::initPkt(), and UwSCTrackerModule::recv().
y()
float & hdr_uwSCFTracker::y () inline
Reference to the y variable.
References y_.
Referenced by UwSCFTrackerModule::initPkt(), and UwSCTrackerModule::recv().
z()
float & hdr_uwSCFTracker::z () inline
Reference to the z variable.
References z_.
Referenced by UwSCFTrackerModule::initPkt(), and UwSCTrackerModule::recv().
Member Data Documentation
mine_remove_
bool hdr_uwSCFTracker::mine_remove_
Check whether mine is removed or not.
Referenced by mine_remove().
offset_
int hdr_uwSCFTracker::offset_ static
Required by the PacketHeaderManager.
Offset used to access in hdr_uwTracker packets header.
Referenced by access(), and offset().
timestamp_
float hdr_uwSCFTracker::timestamp_
Timestamp when the target was detected.
Referenced by timestamp().
x_
float hdr_uwSCFTracker::x_
X coordinate of the mine.
Referenced by x().
y_
float hdr_uwSCFTracker::y_
Y coordinate of the mine.
Referenced by y().
z_
float hdr_uwSCFTracker::z_
Z coordinate of the mine.
Referenced by z().
The documentation for this struct was generated from the following files:
DESERT_Addons/uwswarm_control/uwsc-tracker-follower-packet.h
DESERT_Addons/uwswarm_control/initlib.cc