DESERT: hdr_cooladdon Struct Reference
hdr_cooladdon Struct Reference
#include <cool-addon-hdr.h>
Public Member Functions
double & throughput ()
Static Public Member Functions
static int & offset ()
static struct hdr_cooladdon * access (const Packet *p)
Public Attributes
double throughput_
Static Public Attributes
static int offset_
Member Function Documentation
access()
static struct hdr_cooladdon * hdr_cooladdon::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access(), and CoolAddon::recv().
offset()
static int & hdr_cooladdon::offset () inline static
Reference to the offset_ variable.
References offset_.
throughput()
double & hdr_cooladdon::throughput () inline
References throughput_.
Referenced by CoolAddon::recv(), and CoolAddon::sendTHRWarning().
Member Data Documentation
offset_
int hdr_cooladdon::offset_ static
Required by the PacketHeaderManager
Referenced by access(), and offset().
throughput_
double hdr_cooladdon::throughput_
Parameter used by the protocol
Referenced by throughput().
The documentation for this struct was generated from the following files:
DESERT_Addons/cool-addon/cool-addon-hdr.h
DESERT_Addons/cool-addon/initlib.cpp