DESERT: hdr_uwm_tr Struct Reference
hdr_uwm_tr Struct Reference
#include <uwmulti-traffic-range-crt.h>
Public Member Functions
int & traffic ()
Static Public Member Functions
static int & offset ()
static hdr_uwm_tr * access (const Packet *p)
Public Attributes
int tr_id_
Static Public Attributes
static int offset_
Detailed Description
traffic, counter
Member Function Documentation
access()
static hdr_uwm_tr * hdr_uwm_tr::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
offset()
static int & hdr_uwm_tr::offset () inline static
Reference to the offset_ variable.
References offset_.
traffic()
int & hdr_uwm_tr::traffic () inline
Reference to the traffic ID.
References tr_id_.
Referenced by UwMultiTrafficRangeCtr::checkRange().
Member Data Documentation
offset_
int hdr_uwm_tr::offset_ static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
tr_id_
int hdr_uwm_tr::tr_id_
Id of the traffic app layer.
Referenced by traffic().
The documentation for this struct was generated from the following files:
DESERT_Addons/uwmulti_traffic_control/uwmulti-traffic-range-crt.h
DESERT_Addons/uwmulti_traffic_control/initlib.cc