DESERT: hdr_RTS_UFETCH Struct Reference
hdr_RTS_UFETCH Struct Reference
#include <uwUFetch_cmn_hdr.h>
Public Member Functions
int & num_DATA_pcks ()
int & backoff_time_RTS ()
Static Public Member Functions
static int & offset ()
static hdr_RTS_UFETCH * access (const Packet *p)
Public Attributes
int num_DATA_pcks_
int backoff_time_RTS_
Static Public Attributes
static int offset_ = 0
Detailed Description
Content header of RTS packet
Member Function Documentation
access()
static hdr_RTS_UFETCH * hdr_RTS_UFETCH::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
backoff_time_RTS()
int & hdr_RTS_UFETCH::backoff_time_RTS () inline
Reference to the backoff_Time_RTS_ variable
Returns
int& backoff_time_RTS_
References backoff_time_RTS_.
Referenced by uwUFetch_AUV::RTS_rx(), and uwUFetch_NODE::state_RTS_tx().
num_DATA_pcks()
int & hdr_RTS_UFETCH::num_DATA_pcks () inline
Reference to the num_Data_pcks_ variable
Returns
int& num_DATA_pcks_
References num_DATA_pcks_.
Referenced by uwUFetch_AUV::RTS_rx(), and uwUFetch_NODE::state_RTS_tx().
offset()
static int & hdr_RTS_UFETCH::offset () inline static
Reference to the offset variable
References offset_.
Member Data Documentation
backoff_time_RTS_
int hdr_RTS_UFETCH::backoff_time_RTS_
Backoff time chosen by the HN for collision free
Referenced by backoff_time_RTS(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
num_DATA_pcks_
int hdr_RTS_UFETCH::num_DATA_pcks_
Number of packets that the HN want to transmit to the AUV
Referenced by num_DATA_pcks(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
offset_
int hdr_RTS_UFETCH::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uwUFetch/uwUFetch_cmn_hdr.h
DESERT_Framework/DESERT/data_link/uwUFetch/initlib.cpp