DESERT: hdr_uwicrp_data Struct Reference
hdr_uwicrp_data Struct Reference
#include <uwicrp-hdr-data.h>
Public Member Functions
nsaddr_t * list_of_hops ()
int & pointer_to_list_of_hops ()
int & list_of_hops_length ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwicrp_data * access (const Packet *p)
Public Attributes
nsaddr_t list_of_hops_ [MAX_HOP_NUMBER]
int pointer_to_list_of_hops_
int list_of_hops_length_
Static Public Attributes
static int offset_ = 0
Detailed Description
hdr_uwicrp_data describes data packets used by UWICRP
Member Function Documentation
access()
static struct hdr_uwicrp_data * hdr_uwicrp_data::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
list_of_hops()
nsaddr_t * hdr_uwicrp_data::list_of_hops () inline
Pointer to the list_of_hops_ variable
References list_of_hops_.
Referenced by UwIcrpNode::addIpInList(), UwIcrpNode::initPkt(), UwIcrpSink::initStatusPkt(), and UwIcrpNode::isIpInList().
list_of_hops_length()
int & hdr_uwicrp_data::list_of_hops_length () inline
Reference to the list_of_hops_length_ variable
References list_of_hops_length_.
Referenced by UwIcrpNode::addIpInList(), UwIcrpNode::initPkt(), UwIcrpSink::initStatusPkt(), and UwIcrpNode::isIpInList().
offset()
static int & hdr_uwicrp_data::offset () inline static
Reference to the offset_ variable
References offset_.
pointer_to_list_of_hops()
int & hdr_uwicrp_data::pointer_to_list_of_hops () inline
Reference to the pointer_to_list_of_hops_ variable
References pointer_to_list_of_hops_.
Referenced by UwIcrpNode::addIpInList(), UwIcrpNode::initPkt(), and UwIcrpSink::initStatusPkt().
Member Data Documentation
list_of_hops_
nsaddr_t hdr_uwicrp_data::list_of_hops_[MAX_HOP_NUMBER]
List of IPs saved in the header
Referenced by list_of_hops().
list_of_hops_length_
int hdr_uwicrp_data::list_of_hops_length_
Current number of IPs stored in the header
Referenced by list_of_hops_length().
offset_
int hdr_uwicrp_data::offset_ = 0 static
Required by the PacketHeaderManager
Offset used to access in hdr_uwicrp_data packets header.
Referenced by access(), and offset().
pointer_to_list_of_hops_
int hdr_uwicrp_data::pointer_to_list_of_hops_
Pointer used to keep track of the last IPs processed
Referenced by pointer_to_list_of_hops().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/network/uwicrp/uwicrp-hdr-data.h
DESERT_Framework/DESERT/network/uwicrp/uwicrp.cpp