DESERT: hdr_BEACON_UFETCH Struct Reference
hdr_BEACON_UFETCH Struct Reference
#include <uwUFetch_cmn_hdr.h>
Public Member Functions
int & t_min_bc ()
int & t_max_bc ()
int & num_Max_CBEACON_tx_by_HN ()
Static Public Member Functions
static int & offset ()
static hdr_BEACON_UFETCH * access (const Packet *p)
Public Attributes
int t_min_bc_
int t_max_bc_
int num_Max_CBEACON_tx_by_HN_
Static Public Attributes
static int offset_ = 0
Detailed Description
Content header of BEACON packet
Member Function Documentation
access()
static hdr_BEACON_UFETCH * hdr_BEACON_UFETCH::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
num_Max_CBEACON_tx_by_HN()
int & hdr_BEACON_UFETCH::num_Max_CBEACON_tx_by_HN () inline
Reference to num_Max_CBEACON_tx_by_HN_ variable
Returns
int& num_Max_CBEACON_tx_by_HN_
References num_Max_CBEACON_tx_by_HN_.
Referenced by uwUFetch_NODE::BEACON_rx(), and uwUFetch_NODE::state_BEACON_tx().
offset()
static int & hdr_BEACON_UFETCH::offset () inline static
Reference to the offset variable
References offset_.
t_max_bc()
int & hdr_BEACON_UFETCH::t_max_bc () inline
Reference to t_max_bc_ variable
Returns
int& t_max_bc_
References t_max_bc_.
Referenced by uwUFetch_NODE::BEACON_rx(), and uwUFetch_NODE::state_BEACON_tx().
t_min_bc()
int & hdr_BEACON_UFETCH::t_min_bc () inline
Reference to t_min_bc_ variable
Returns
int& t_min_bc_
References t_min_bc_.
Referenced by uwUFetch_NODE::BEACON_rx(), and uwUFetch_NODE::state_BEACON_tx().
Member Data Documentation
num_Max_CBEACON_tx_by_HN_
int hdr_BEACON_UFETCH::num_Max_CBEACON_tx_by_HN_
Maximum number of CBEACON that the HN can transmit after the BEACON packet
Referenced by num_Max_CBEACON_tx_by_HN(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
offset_
int hdr_BEACON_UFETCH::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
t_max_bc_
int hdr_BEACON_UFETCH::t_max_bc_
maximum value in which the Node can choose his backoff time
Referenced by packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), t_max_bc(), and packer_uwUFetch::unpackMyHdr().
t_min_bc_
int hdr_BEACON_UFETCH::t_min_bc_
minimum value in which the Node can choose his backoff time
Referenced by packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), t_min_bc(), and packer_uwUFetch::unpackMyHdr().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uwUFetch/uwUFetch_cmn_hdr.h
DESERT_Framework/DESERT/data_link/uwUFetch/initlib.cpp