DESERT: hdr_uwROV_monitoring Struct Reference
hdr_uwROV_monitoring Struct Reference
#include <uwrov-packet.h>
Public Member Functions
float & x ()
float & y ()
float & z ()
double & ack ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwROV_monitoring * access (const Packet *p)
Public Attributes
float x_
float y_
float z_
double ack_
Static Public Attributes
static int offset_
Detailed Description
hdr_uwROV_monitoring describes UWROV_monitoring packets sent by the ROV to the base station for monitoring the ROV state.
Member Function Documentation
access()
static struct hdr_uwROV_monitoring * hdr_uwROV_monitoring::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
ack()
double & hdr_uwROV_monitoring::ack () inline
References ack_.
Referenced by UwROVModule::initPkt(), and UwROVCtrModule::recv().
offset()
static int & hdr_uwROV_monitoring::offset () inline static
Reference to the offset_ variable.
References offset_.
x()
float & hdr_uwROV_monitoring::x () inline
References x_.
Referenced by UwROVModule::initPkt(), UwROVCtrModule::recv(), and UwSCROVCtrModule::recv().
y()
float & hdr_uwROV_monitoring::y () inline
References y_.
Referenced by UwROVModule::initPkt(), UwROVCtrModule::recv(), and UwSCROVCtrModule::recv().
z()
float & hdr_uwROV_monitoring::z () inline
References z_.
Referenced by UwROVModule::initPkt(), UwROVCtrModule::recv(), and UwSCROVCtrModule::recv().
Member Data Documentation
ack_
double hdr_uwROV_monitoring::ack_
Referenced by ack().
offset_
int hdr_uwROV_monitoring::offset_ static
Required by the PacketHeaderManager.
Offset used to access in hdr_uwROV packets header.
Referenced by access(), and offset().
x_
float hdr_uwROV_monitoring::x_
Referenced by x().
y_
float hdr_uwROV_monitoring::y_
Referenced by y().
z_
float hdr_uwROV_monitoring::z_
Referenced by z().
The documentation for this struct was generated from the following files:
DESERT_Addons/uwrov/uwrov-packet.h
DESERT_Addons/uwrov/uwrov-module.cc