DESERT: hdr_uwip Struct Reference
hdr_uwip Struct Reference
#include <uwip-module.h>
Public Member Functions
uint8_t & saddr ()
uint8_t & daddr ()
Static Public Member Functions
static int & offset ()
static hdr_uwip * access (const Packet *p)
Public Attributes
uint8_t saddr_
uint8_t daddr_
Static Public Attributes
static int offset_
Detailed Description
hdr_uwip describes UWIP packets.
Member Function Documentation
access()
static hdr_uwip * hdr_uwip::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access(), UwCbrModule::initPkt(), UwVbrModule::initPkt(), UwTrackerModule::printReceivedPacket(), and UwCbrModule::printReceivedPacket().
daddr()
uint8_t & hdr_uwip::daddr () inline
Reference to the daddr_ variable.
References daddr_.
Referenced by SunIPRoutingNode::bufferManager(), UwMultiTrafficRangeCtr::checkRange(), SunIPRoutingNode::createRouteError(), UwPosBasedRt::findNextHop(), SunIPRoutingNode::forwardDataPacket(), UwMultiDestination::getDestinationLayer(), UwIcrpNode::initPkt(), UwCbrModule::initPkt(), UwVbrModule::initPkt(), UwPosBasedRt::initPkt(), UwIcrpNode::initPktAck(), SunIPRoutingNode::initPktDataPacket(), SunIPRoutingNode::initPktPathEstAnswer(), SunIPRoutingNode::initPktPathEstSearch(), UwIcrpSink::initStatusPkt(), packerUWIP::printMyHdrFields(), UwTrackerModule::printReceivedPacket(), UwCbrModule::printReceivedPacket(), UwFloodingSec::recv(), UwFlooding::recv(), UwIcrpNode::recv(), SunIPRoutingNode::recv(), SunIPRoutingSink::recv(), UwStaticRoutingModule::recv(), UWIPModule::recv(), UwPosBasedRt::recv(), UwPosBasedRtROV::recv(), UwMultiTrafficRangeCtr::recv(), UwMultiPhyControl::recvFromLowerLayers(), UwMultiPhyControl::recvFromUpperLayers(), SunIPRoutingNode::replyPathEstSearch(), SunIPRoutingNode::sendBackAck(), SunIPRoutingSink::sendBackAck(), UwIcrpNode::sendBackAck(), UwIcrpSink::sendBackAck(), UWMllModule::sendDown(), UwFloodingSec::sendDown(), UwMultiPhyControl::sendPing(), SunIPRoutingSink::sendProbe(), SunIPRoutingNode::sendRouteBack(), SunIPRoutingNode::sendRouteErrorBack(), SunIPRoutingNode::tracePacket(), SunIPRoutingSink::tracePacket(), uwApplicationModule::transmit(), packerUWIP::unpackMyHdr(), SunIPRoutingSink::writePathInTrace(), UwFloodingSec::writePathInTrace(), and UwFlooding::writePathInTrace().
offset()
static int & hdr_uwip::offset () inline static
Reference to the offset_ variable.
References offset_.
saddr()
uint8_t & hdr_uwip::saddr () inline
Reference to the saddr_ variable.
References saddr_.
Referenced by UwIcrpNode::addRouteEntry(), SunIPRoutingNode::answerPath(), SunIPRoutingNode::bufferManager(), UwMultiTrafficRangeCtr::checkRange(), SunIPRoutingNode::createRouteError(), SunIPRoutingNode::evaluatePath(), SunIPRoutingNode::forwardDataPacket(), SunIPRoutingNode::initPktDataPacket(), SunIPRoutingNode::initPktPathEstAnswer(), UwIcrpSink::initStatusPkt(), packerUWIP::printMyHdrFields(), UwTrackerModule::printReceivedPacket(), UwCbrModule::printReceivedPacket(), SunIPRoutingNode::receiveProbe(), UwFloodingSec::recv(), UwFlooding::recv(), SunIPRoutingNode::recv(), SunIPRoutingSink::recv(), UwUdp::recv(), UWIPModule::recv(), UwMultiTrafficRangeCtr::recv(), UwMultiPhyControl::recvFromLowerLayers(), SunIPRoutingNode::replyPathEstSearch(), UwMultiPhyControl::sendPing(), SunIPRoutingSink::sendProbe(), SunIPRoutingNode::sendRouteBack(), SunIPRoutingNode::tracePacket(), SunIPRoutingSink::tracePacket(), packerUWIP::unpackMyHdr(), SunIPRoutingSink::writePathInTrace(), UwFloodingSec::writePathInTrace(), and UwFlooding::writePathInTrace().
Member Data Documentation
daddr_
uint8_t hdr_uwip::daddr_
IP of the destination.
Referenced by daddr(), packerUWIP::packMyHdr(), and packerUWIP::unpackMyHdr().
offset_
int hdr_uwip::offset_ static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
saddr_
uint8_t hdr_uwip::saddr_
IP of the source.
Referenced by packerUWIP::packMyHdr(), saddr(), and packerUWIP::unpackMyHdr().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/network/uwip/uwip-module.h
DESERT_Framework/DESERT/network/uwip/uwip-module.cpp