DESERT: hdr_uwopticalbeampattern Struct Reference
hdr_uwopticalbeampattern Struct Reference
#include <uwopticalbeampattern-hdr.h>
Public Member Functions
double & get_inclination_angle ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwopticalbeampattern * access (const Packet *p)
Public Attributes
double inclination_angle_
Static Public Attributes
static int offset_ = 0
Member Function Documentation
access()
static struct hdr_uwopticalbeampattern * hdr_uwopticalbeampattern::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
get_inclination_angle()
double & hdr_uwopticalbeampattern::get_inclination_angle () inline
References inclination_angle_.
Referenced by UwOpticalBeamPattern::getBetaTx(), UwOpticalBeamPattern::getBetaXYTx(), and UwOpticalBeamPattern::startTx().
offset()
static int & hdr_uwopticalbeampattern::offset () inline static
Reference to the offset_ variable.
References offset_.
Member Data Documentation
inclination_angle_
double hdr_uwopticalbeampattern::inclination_angle_
inclination angle of the soruce modem.
Referenced by get_inclination_angle().
offset_
int hdr_uwopticalbeampattern::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/physical/uwopticalbeampattern/uwopticalbeampattern-hdr.h
DESERT_Framework/DESERT/physical/uwopticalbeampattern/initlib.cpp