DESERT: hdr_TRIGGER_UFETCH Struct Reference
hdr_TRIGGER_UFETCH Struct Reference
#include <uwUFetch_cmn_hdr.h>
Public Member Functions
int & t_min ()
int & t_max ()
int & max_pck_want_rx ()
Static Public Member Functions
static int & offset ()
static hdr_TRIGGER_UFETCH * access (const Packet *p)
Public Attributes
int t_min_
int t_max_
int max_pck_want_rx_
Static Public Attributes
static int offset_ = 0
Detailed Description
Content header of TRIGGER packet
Member Function Documentation
access()
static hdr_TRIGGER_UFETCH * hdr_TRIGGER_UFETCH::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
max_pck_want_rx()
int & hdr_TRIGGER_UFETCH::max_pck_want_rx () inline
Reference to the max_pck_want_rx variable
Returns
int & max_pck_want_rx_
References max_pck_want_rx_.
Referenced by uwUFetch_AUV::state_TRIGGER_tx(), uwUFetch_AUV::state_TRIGGER_tx_without(), uwUFetch_NODE::TRIGGER_rx(), and uwUFetch_NODE::TRIGGER_rx_without().
offset()
static int & hdr_TRIGGER_UFETCH::offset () inline static
Reference to the offset variable
References offset_.
t_max()
int & hdr_TRIGGER_UFETCH::t_max () inline
Reference to the t_max variable
Returns
int& t_max_
References t_max_.
Referenced by uwUFetch_AUV::state_TRIGGER_tx(), uwUFetch_AUV::state_TRIGGER_tx_without(), uwUFetch_NODE::TRIGGER_rx(), and uwUFetch_NODE::TRIGGER_rx_without().
t_min()
int & hdr_TRIGGER_UFETCH::t_min () inline
Reference to the t_min variable
Returns
int& t_min_
References t_min_.
Referenced by uwUFetch_AUV::state_TRIGGER_tx(), uwUFetch_AUV::state_TRIGGER_tx_without(), uwUFetch_NODE::TRIGGER_rx(), and uwUFetch_NODE::TRIGGER_rx_without().
Member Data Documentation
max_pck_want_rx_
int hdr_TRIGGER_UFETCH::max_pck_want_rx_
Maximum number of pck that AUV want receive from sink
Referenced by max_pck_want_rx(), packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), and packer_uwUFetch::unpackMyHdr().
offset_
int hdr_TRIGGER_UFETCH::offset_ = 0 static
Required by the PacketHeaderManager.
Referenced by access(), and offset().
t_max_
int hdr_TRIGGER_UFETCH::t_max_
maximum value in which the HN can choose his backoff time
Referenced by packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), t_max(), and packer_uwUFetch::unpackMyHdr().
t_min_
int hdr_TRIGGER_UFETCH::t_min_
minimum value in which the HN can choose his backoff time
Referenced by packer_uwUFetch::packMyHdr(), packer_uwUFetch::printMyHdrFields(), t_min(), and packer_uwUFetch::unpackMyHdr().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uwUFetch/uwUFetch_cmn_hdr.h
DESERT_Framework/DESERT/data_link/uwUFetch/initlib.cpp