DESERT: hdr_uwflooding Struct Reference
hdr_uwflooding Struct Reference
#include <uwflooding-hdr.h>
Public Member Functions
uint8_t & ttl ()
uint8_t & ttl ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwflooding * access (const Packet *p)
static int & offset ()
static struct hdr_uwflooding * access (const Packet *p)
Public Attributes
uint8_t ttl_
Static Public Attributes
static int offset_ = 0
Detailed Description
hdr_uwflooding describes packets used by UWFLOODING.
Member Function Documentation
access() [1/2]
static struct hdr_uwflooding * hdr_uwflooding::access (const Packet * p) inline static
References access(), and offset_.
access() [2/2]
static struct hdr_uwflooding * hdr_uwflooding::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
offset() [1/2]
static int & hdr_uwflooding::offset () inline static
Reference to the offset_ variable.
References offset_.
offset() [2/2]
static int & hdr_uwflooding::offset () inline static
Reference to the offset_ variable.
References offset_.
ttl() [1/2]
uint8_t & hdr_uwflooding::ttl () inline
Reference to the uid_ variable.
References ttl_.
ttl() [2/2]
uint8_t & hdr_uwflooding::ttl () inline
Reference to the uid_ variable.
References ttl_.
Referenced by PackerUwFlooding::packMyHdr(), PackerUwFlooding::printMyHdrFields(), UwFloodingSec::recv(), UwFlooding::recv(), PackerUwFlooding::unpackMyHdr(), UwFloodingSec::writePathInTrace(), and UwFlooding::writePathInTrace().
Member Data Documentation
offset_
int hdr_uwflooding::offset_ = 0 static
Required by the PacketHeaderManager.
Offset used to access in hdr_uwflooding packets header.
Referenced by access(), and offset().
ttl_
uint8_t hdr_uwflooding::ttl_
Time to leave of the packet.
Referenced by ttl().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/network/uwflooding/uwflooding-hdr.h
DESERT_Addons/security/uwflooding_sec/uwflooding-hdr.h
DESERT_Framework/DESERT/network/uwflooding/uwflooding.cpp
DESERT_Addons/security/uwflooding_sec/uwflooding-sec.cpp