DESERT: hdr_AUV_MULE Struct Reference
hdr_AUV_MULE Struct Reference
#include <uwpolling_cmn_hdr.h>
Public Member Functions
uint16_t & pkt_uid ()
uint16_t & last_pkt_uid ()
Static Public Member Functions
static int & offset ()
static struct hdr_AUV_MULE * access (const Packet *p)
Public Attributes
uint16_t pkt_uid_
uint16_t last_pkt_uid_
Static Public Attributes
static int offset_ = 0
Detailed Description
Header of the data sent from AUV MULE to SINK
Member Function Documentation
access()
static struct hdr_AUV_MULE * hdr_AUV_MULE::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
last_pkt_uid()
uint16_t & hdr_AUV_MULE::last_pkt_uid () inline
Reference to the last_pkt_uid_ variable
References last_pkt_uid_.
Referenced by Uwpolling_SINK::stateRxData(), and Uwpolling_AUV::stateTxData().
offset()
static int & hdr_AUV_MULE::offset () inline static
Reference to the offset variable
References offset_.
pkt_uid()
uint16_t & hdr_AUV_MULE::pkt_uid () inline
Reference to the pkt_uid_ variable
References pkt_uid_.
Referenced by Uwpolling_AUV::handleAck(), Uwpolling_AUV::handleProbeAck(), Uwpolling_AUV::recvFromUpperLayers(), Uwpolling_SINK::stateRxData(), and Uwpolling_AUV::stateTx().
Member Data Documentation
last_pkt_uid_
uint16_t hdr_AUV_MULE::last_pkt_uid_
Referenced by last_pkt_uid(), packerUwpolling::packMyHdr(), packerUwpolling::printMyHdrFields(), and packerUwpolling::unpackMyHdr().
offset_
int hdr_AUV_MULE::offset_ = 0 static
ID of the last packet transmitted in the round Required by the PacketHeaderManager.
Referenced by access(), and offset().
pkt_uid_
uint16_t hdr_AUV_MULE::pkt_uid_
unique ID of the transmitted packet by the AUV node
Referenced by packerUwpolling::packMyHdr(), pkt_uid(), packerUwpolling::printMyHdrFields(), and packerUwpolling::unpackMyHdr().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/data_link/uwpolling/uwpolling_cmn_hdr.h
DESERT_Framework/DESERT/data_link/uwpolling/initlib.cpp