DESERT: hdr_uwal Struct Reference
hdr_uwal Struct Reference
#include <hdr-uwal.h>
Public Member Functions
uint8_t & srcID ()
unsigned int & pktID ()
uint16_t & framePayloadOffset ()
uint8_t & Mbit ()
char * dummyStr ()
char * binPkt ()
uint32_t & binPktLength ()
uint32_t & binHdrLength ()
Static Public Member Functions
static int & offset ()
static struct hdr_uwal * access (const Packet *p)
Public Attributes
uint8_t srcID_
unsigned int pktID_
uint16_t framePayloadOffset_
uint8_t Mbit_
char dummyStr_ [MAX_DUMMY_STRING_LENGTH]
char binPkt_ [MAX_BIN_PKT_ARRAY_LENGTH]
uint32_t binPktLength_
uint32_t binHdrLength_
Static Public Attributes
static int offset_
Detailed Description
hdr_uwal describes the packet header used by Uwal objects.
Member Function Documentation
access()
static struct hdr_uwal * hdr_uwal::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
binHdrLength()
uint32_t & hdr_uwal::binHdrLength () inline
Reference to the binHdrLength_ variable.
References binHdrLength_.
Referenced by Uwal::checkRxFrameSet(), Uwal::fragmentPkt(), Uwal::initializeHdr(), packer::packHdr(), Uwal::reassembleFrames(), packer::unpackHdr(), and packer::unpackPayload().
binPkt()
char * hdr_uwal::binPkt () inline
Return to the binPkt_ array pointer.
References binPkt_.
Referenced by Uwal::checkRxFrameSet(), UwAhoiModem::createRxPacket(), UwEvoLogicsS2CModem::createRxPacket(), UwMODAModem::createRxPacket(), UwModemCSA::createRxPacket(), UWMPhy_modem::endRx(), UwAhoiModem::fillAhoiPkt(), Uwal::fragmentPkt(), Uwal::initializeHdr(), packer::packHdr(), packer::packPayload(), Uwal::reassembleFrames(), UWMPhy_modem::recv(), UwEvoLogicsS2CModem::startTx(), UwMODAModem::startTx(), UwModemCSA::startTx(), packer::unpackHdr(), and packer::unpackPayload().
binPktLength()
uint32_t & hdr_uwal::binPktLength () inline
Reference to the binPktLength_ variable.
References binPktLength_.
Referenced by Uwal::checkRxFrameSet(), UwAhoiModem::createRxPacket(), UwEvoLogicsS2CModem::createRxPacket(), UwMODAModem::createRxPacket(), UwModemCSA::createRxPacket(), UWMPhy_modem::endRx(), UwAhoiModem::fillAhoiPkt(), Uwal::fragmentPkt(), UwEvoLogicsS2CModem::getTxDuration(), UwMODAModem::getTxDuration(), Uwal::initializeHdr(), packer::packHdr(), packer::packPayload(), Uwal::reassembleFrames(), UWMPhy_modem::recv(), UwEvoLogicsS2CModem::startTx(), UwMODAModem::startTx(), UwModemCSA::startTx(), and packer::unpackPayload().
dummyStr()
char * hdr_uwal::dummyStr () inline
Return the pointer to the dummyStr_ array.
References dummyStr_.
Referenced by Uwal::initializeHdr(), and packer::printMyHdrField().
framePayloadOffset()
uint16_t & hdr_uwal::framePayloadOffset () inline
Reference to the frameOffset_ variable.
References framePayloadOffset_.
Referenced by Uwal::fragmentPkt(), Uwal::initializeHdr(), packer::printMyHdrField(), and Uwal::reassembleFrames().
Mbit()
uint8_t & hdr_uwal::Mbit () inline
Reference to the Mbit_ variable.
References Mbit_.
Referenced by Uwal::fragmentPkt(), Uwal::initializeHdr(), packer::printMyHdrField(), Uwal::reassembleFrames(), Uwal::recvSyncClMsg(), and Uwal::startTx().
offset()
static int & hdr_uwal::offset () inline static
References offset_.
pktID()
unsigned int & hdr_uwal::pktID () inline
Reference to the pktID_ variable.
References pktID_.
Referenced by Uwal::fragmentPkt(), Uwal::initializeHdr(), packer::printMyHdrField(), and Uwal::reassembleFrames().
srcID()
uint8_t & hdr_uwal::srcID () inline
Reference to the srcID_ variable.
References srcID_.
Referenced by Uwal::checkRxFrameSet(), Uwal::initializeHdr(), packer::printMyHdrField(), Uwal::reassembleFrames(), and UwAhoiModem::storePacketInfo().
Member Data Documentation
binHdrLength_
uint32_t hdr_uwal::binHdrLength_
number of chars in binPkt_ to consider as header.
Referenced by binHdrLength().
binPkt_
char hdr_uwal::binPkt_[MAX_BIN_PKT_ARRAY_LENGTH]
array to store binary data as encoded from or to be decoded to this NS-Miracle packet header (NOTE: this CANNOT be fragmented) and the active packers linked to packer.
See also
classes packer and uwmphy_modem
Referenced by binPkt().
binPktLength_
uint32_t hdr_uwal::binPktLength_
number of chars in binPkt_ to consider.
Referenced by binPktLength().
dummyStr_
char hdr_uwal::dummyStr_[MAX_DUMMY_STRING_LENGTH]
array containing a dummy string.
Referenced by dummyStr(), packer::packMyHdr(), and packer::unpackMyHdr().
framePayloadOffset_
uint16_t hdr_uwal::framePayloadOffset_
Offset of the frame payload.
Referenced by framePayloadOffset(), packer::packMyHdr(), and packer::unpackMyHdr().
Mbit_
uint8_t hdr_uwal::Mbit_
M bit: if set to 0 the current frame is the last or the only one; if set to 1 the current frame is not the last.
Referenced by Mbit(), packer::packMyHdr(), and packer::unpackMyHdr().
offset_
int hdr_uwal::offset_ static
Referenced by access(), and offset().
pktID_
unsigned int hdr_uwal::pktID_
ID of the packet.
Referenced by packer::packMyHdr(), pktID(), and packer::unpackMyHdr().
srcID_
uint8_t hdr_uwal::srcID_
ID of the packet's source node.
Referenced by packer::packMyHdr(), srcID(), and packer::unpackMyHdr().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/physical/uw-al/hdr-uwal.h
DESERT_Framework/DESERT/physical/uw-al/hdr-uwal.cpp