DESERT: hdr_sun_ack Struct Reference
hdr_sun_ack Struct Reference
#include <sun-hdr-ack.h>
Public Member Functions
int & uid ()
Static Public Member Functions
static int & offset ()
static struct hdr_sun_ack * access (const Packet *p)
Public Attributes
int uid_
Static Public Attributes
static int offset_
Detailed Description
hdr_sun_ack describes acks packets used by UWSUN.
Member Function Documentation
access()
static struct hdr_sun_ack * hdr_sun_ack::access (const Packet * p) inline static
References access(), and offset_.
Referenced by access().
offset()
static int & hdr_sun_ack::offset () inline static
Reference to the offset_ variable.
References offset_.
uid()
int & hdr_sun_ack::uid () inline
Reference to the uid_ variable.
References uid_.
Referenced by SunIPRoutingNode::recv(), SunIPRoutingNode::sendBackAck(), SunIPRoutingSink::sendBackAck(), SunIPRoutingNode::tracePacket(), and SunIPRoutingSink::tracePacket().
Member Data Documentation
offset_
int hdr_sun_ack::offset_ static
Initial value:
=
        0
Required by the PacketHeaderManager.
Offset used to access in hdr_sun_ack packets header.
Referenced by access(), and offset().
uid_
int hdr_sun_ack::uid_
Uid of the packet acked.
Referenced by uid().
The documentation for this struct was generated from the following files:
DESERT_Framework/DESERT/network/uwsun/sun-hdr-ack.h
DESERT_Framework/DESERT/network/uwsun/sun-ipr.cpp