DESERT: DESERT_Addons/uwmulti_traffic_control/uwmulti-multiphy-controller.h File Reference
uwmulti-multiphy-controller.h File Reference
Definition of UwMultiPhyControl class.
Classes
struct LocalConnection
struct RemoteConnection
class PriorityMap
class UwMultiPhyControl
class UwMultiPhyControl::ResilienceTimer
class UwMultiPhyControl::ProbeTimer
Enumerations
enum LinkStatus { LINK_UNKNOWN , LINK_OK , LINK_PROBING }
Functions
std::string printType (packet_t ptype)
std::ostream & operator<< (std::ostream &o, LinkStatus s)
Detailed Description
Definition of UwMultiPhyControl class.
Author
Enrico Lovisotto
Version
1.0.0
Enumeration Type Documentation
LinkStatus
enum LinkStatus
Enumerator
LINK_UNKNOWN
LINK_OK
LINK_PROBING
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & o, LinkStatus s)
References LINK_OK, LINK_PROBING, and LINK_UNKNOWN.
printType()
std::string printType (packet_t ptype)
References PT_UWMULTIPHY_DATA, PT_UWMULTIPHY_PING, and PT_UWMULTIPHY_PONG.
Referenced by UwMultiPhyControl::recvFromLowerLayers(), UwMultiPhyControl::recvFromUpperLayers(), and UwMultiPhyControl::sendPing().